
import { Project, ProjectCategory, AwardType } from './types';

export const COLORS = {
  PRIMARY: '#EF3340', // PANTONE 2034 C
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  TEAL: '#00AFAD',    // PANTONE 3258 C
  LIME: '#84BD00',    // PANTONE 7487 C
  YELLOW: '#FEDD00',  // PANTONE YELLOW C
  ORANGE: '#E89923',  // PANTONE 7411 C
  MAGENTA: '#DF1995', // PANTONE 218 C
  PURPLE: '#802FDE',  // PANTONE 2593 C
};

export const PARTNERS = [
  'A.C. Camargo','Airis Tecnologia','Akaer','Binario Cloud','Boldr','BYX','CTI Renato Archer','Dell Technologies', 'Embraer', 'Fanatee','Hospital Sírio-Libanês',
  'HP','IPT','Intelbras','J.ASSY','Mercedes-Benz','Mottu','Rockwell Automation','Tata Consultancy Services','WEG','ABB','Ambev','Cicloway',
  'Embrapa','Fiberbus','Fintalk','IBM Brasil','MASP','Maxion Structural Components','NTT Data Brasil','Mevo','Syngenta Seeds','Versa Fuel'
].sort();

export const MOCK_PROJECTS: Project[] = [
  {
    id: '202502001',
    title: 'Impressão 3D de estabilizador bucal para radioterapia',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.BIOENGENHARIA,
    thumbnailUrl: 'https://accamargo.org.br/sites/default/files/styles/imagem_redonda_home/public/location/2020-08/unidades-pires.jpg?h=bc835eb6&itok=WxHi5Dlt',
    videoUrl: '',
    galleryUrls: [
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1351', name: 'Bruno Alencar Braghette', role: 'Engenharia Mecânica' },
      { id: '1422', name: 'Paulo Augusto dos Passos Oliveira', role: 'Engenharia Mecânica' },
      { id: '1358', name: 'Daniel Vergamini Luna Frussa', role: 'Engenharia Mecânica' },
      { id: '1437', name: 'Ruy de Paula Souza Neto', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Dispositivos como bolus e estabilizador bucal são utilizados durante a radioterapia para melhor eficácia do tratamento. O estabilizador bucal e o bolus (utilizado em outras áreas do corpo) são métodos pioneiros do A.C.Camargo que permitem um posicionamento adequado do paciente durante a sessão de radioterapia, o qual é essencial para garantir a precisão na entrega da dose de radiação ao tumor, minimizando danos aos tecidos saudáveis. O bolus e o estabilizador bucal garantem um posicionamento consistente em cada sessão e visam também o conforto do paciente. Esses materiais são produzidos na fase de planejamento do tratamento, com apoio de imagens como tomografias e ressonâncias, para definir o posicionamento ideal e a área exata a ser tratada e definindo o formato, molde e dimensões do bolus ou estabilizador. Após medições, a equipe segue para a confecção dos dispositivos que é feita de forma individual e artesanal. A equipe desprende algumas horas na confecção dos mesmos. Em resumo, o posicionamento do paciente influencia diretamente a eficácia e a segurança do tratamento, sendo essencial a colaboração entre o paciente, o oncologista e a equipe de radioterapia. Desta forma, o objetivo desta proposta seria customizar a confecção destes dispositivos. Nesta proposta teria a inclusão de pacientes com indicação de confecção do estabilizador bucal e bolus.',
    tags: ['3Dprinting','Bioengineering','PatientExperience'],
    partner: 'A.C. Camargo'
  },
  {
    id: '202502002',
    title: 'Mapeamento de produtos em supermercado',
    description: 'Criação de um sistema de mapeamento dinâmico e adaptativo que reconstrói a planta do supermercado e otimiza rotas com base na análise autônoma do fluxo e comportamento dos carrinhos de compras.',
    semester: '2',
    year: 2025,
    category: ProjectCategory.EMBARCADOS,
    thumbnailUrl: 'https://media.licdn.com/dms/image/v2/D4D0BAQG89u7a-qc-mg/company-logo_200_200/B4DZUl2CxbHkAI-/0/1740096679438/airis_tecnologia_logo?e=1778112000&v=beta&t=CxWB886z4esYN8cf0JN8YoJL8Ecz3iqnx5mlrw4K9ZY',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1342', name: 'Ananda Julia Galvão Campêlo', role: 'Engenharia de Computação' },
      { id: '1186', name: 'Kevin Nagayuki Shinohara', role: 'Engenharia de Computação' },
      { id: '591', name: 'Luca Cazzolato Machado', role: 'Engenharia de Computação' },      
      { id: '1441', name: 'Thiago Gonçalves Guadagnoli de Sousa', role: 'Engenharia de Computação' },      

    ],
    advisor: 'Vinicius Licks',
    longDescription: 'Criação de um sistema de mapeamento dinâmico e inteligente que reconstrói a planta de supermercados e otimiza rotas a partir do comportamento de fluxo dos carrinhos.',
    tags: ['ComputerVision', 'IoT', 'DataScience'],
    partner: 'Airis Tecnologia'
  },
  {
    id: '202502003',
    title: 'Desenvolvimento de Navegação Autônoma para VANT Utilizando Técnicas de Aprendizado por Reforço',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.ROBOTICA,
    thumbnailUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS0KoegQUJ9WxFLSH_V59aOFYUWfEseiUjqg&s',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1384', name: 'Henrique Turco Gera', role: 'Ciência da Computação' },
      { id: '1408', name: 'Luigi Orlandi Quinze', role: 'Ciência da Computação' },
      { id: '1445', name: 'Victoria Leal Garcia de Souza', role: 'Engenharia Mecatrônica' },      
      { id: '1399', name: 'Leonardo Sterman Freitas', role: 'Ciência da Computação' },      

    ],
    advisor: 'Fabricio Jailson Barth',
    longDescription: 'Este projeto visa desenvolver, em simulação, um sistema de navegação para um VANT (Veículo Aéreo Não Tripulado) de asa fixa utilizando aprendizado por reforço. (Reinforcement Learning). O ambiente de treinamento foi implementado diretamente sobre a modelagem mecânica do VANT (Aerosonde), no referencial NED (North-East-Down), garantindo que a dinâmica (atuadores, restrições e equações de movimento) utilizada pelo VANT reflita seu comportamento físico. O veículo emprega Proximal Policy Optimization (PPO), adequado a espaços de ação contínuos (complexos) e estáveis para controle fino, aprendendo a minimizar distância ao alvo (waypoint), alinhar direção e respeitar os limites operacionais. Em paralelo, a modelagem mecânica foi consolidada (MATLAB) para validação e análise, enquanto o ambiente em Python (compatível com a biblioteca Gymnasium) integra o mesmo conjunto de equações ao loop de interação do aprendizado por reforço. Essa integração do modelo mecânico com o ambiente de Reinforcement Learning assegura consistência entre simulação física e aprendizado, favorecendo a transferência de resultados e a avaliação comparativa de algoritmos.',
    tags: ['DataScience', 'Simulation', 'ReinforcementLearning'],
    partner: 'Akaer'
  },
  {
    id: '202502004',
    title: 'Monitoramento de rede em máquinas virtuais em uma infraestrutura OpenStack Kolla-Ansible',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CLOUD_COMPUTING,
    thumbnailUrl: 'https://cdn.prod.website-files.com/643d2eea03135260bdaca209/6585cea39ae01230757b9f31_QuantumCloud.webp',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1432', name: 'Raphael Cavalcanti Banov', role: 'Engenharia de Computação' },
      { id: '1391', name: 'João Pedro Gardenal Sarti', role: 'Ciência da Computação' },
      { id: '1355', name: 'Carlos Eduardo Porciuncula Yamada', role: 'Engenharia de Computação' },            
    ],
    advisor: 'Tiago Augusto Orcajo Demay Cordeiro',
    longDescription: 'Desenvolvimento de uma ferramenta independente para monitoramento granular de tráfego em nuvem OpenStack, capaz de distinguir fluxos internos e externos para identificação proativa de anomalias.',
    tags: ['Cloud', 'OpenStack', 'Networking'],
    partner: 'Binario Cloud'
  },
  {
    id: '202502005',
    title: 'Widget Launchpad: Design, Build & Ship with Boldr',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://play-lh.googleusercontent.com/fP2wyT-MmhqYChvbykVtOrIxdYMWHrYZJX2kE4bFD373e7rufv8lnAxFFwHrRNu_Hm5z',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1403', name: 'Luca Santana Feltrin', role: 'Ciência da Computação' },
      { id: '1362', name: 'Eduardo Takei Yaginuma', role: 'Ciência da Computação' },
      { id: '1364', name: 'Esther Caroline Cunha Rodrigues', role: 'Ciência da Computação' },      
      { id: '1370', name: 'Gabriel Fernando Missaka Mendes', role: 'Ciência da Computação' },      

    ],
    advisor: 'Luiz Fernando Cardoso dos Santos Durão',
    longDescription: 'Desenvolvimento e lançamento de widgets mobile multiplataforma focados em design, vivenciando o ciclo completo de entrega de software e métricas de usuário em um ambiente real de startup.',
    tags: ['MobileDevelopment'],
    partner: 'Boldr'
  },
  {
    id: '202502006',
    title: 'Diagnóstico de Dados Aplicado ao Fluxo de Empréstimo Consignado Público',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://marcaspelomundo.com.br/wp-content/uploads/2025/06/unnamed-file-1024x583.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1423', name: 'Pedro Antônio Braga Dutra', role: 'Engenharia de Computação' },
      { id: '1369', name: 'Fernando Pinheiro Silva Fernandes de Mattos', role: 'Engenharia de Computação' },
      { id: '1438', name: 'Sérgio Carmelo Torres Filho', role: 'Engenharia de Computação' },            
    ],
    advisor: 'Raul Ikeda Gomes da Silva',
    longDescription: 'Aplicação de diagnóstico de dados e inteligência analítica para identificar gargalos e aumentar a taxa de conversão na esteira de originação de crédito consignado.',
    tags: ['DataScience'],
    partner: 'BYX'
  },
  {
    id: '202502007',
    title: 'Otimização de uma CPU RISC-V',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.EMBARCADOS,
    thumbnailUrl: 'https://www.forumcampinas.org.br/interdependencia/wp-content/uploads/2023/11/CTI-2023-entrada.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1398', name: 'Leonardo Merlin Paloschi', role: 'Engenharia de Computação' },
      { id: '1427', name: 'Pedro Pereira Cecílio Ventura', role: 'Engenharia de Computação' },
      { id: '1405', name: 'Lucas Fernando de Souza Lima', role: 'Engenharia de Computação' },
      { id: '1386', name: 'Ilana Chaia Finger', role: 'Engenharia de Computação' },            
            
    ],
    advisor: 'Rafael Corsi Ferrão',
    longDescription: 'Otimização de hardware e software de uma CPU RISC-V em VHDL para aumentar o desempenho e a confiabilidade de sistemas de processamento em satélites.',
    tags: ['ComputerArchitecture','EmbeddedSystems'],
    partner: 'CTI Renato Archer'
  },
  {
    id: '202502008',
    title: 'Um framework para avaliação de Vision Language Models',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/34/RR1-_Dell_Campus.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1383', name: 'Henrique Scofield Sotto Mayor', role: 'Ciência da Computação' },
      { id: '1363', name: 'Ellen Coutinho Lião da Silva', role: 'Engenharia de Computação' },
      { id: '1227', name: 'Rodrigo Eiji Furukawa', role: 'Engenharia Mecatrônica' },
      { id: '1409', name: 'Luis Antonio Santana Rodrigues', role: 'Engenharia de Computação' },            
            
    ],
    advisor: 'Fabio Jose Ayres',
    longDescription: 'Desenvolvimento de um framework modular em Python para avaliação sistemática de modelos multimodais (VLMs) em tarefas de interpretação e resposta sobre conteúdos de vídeo.',
    tags: ['VLM','ComputerVision','DeepLearning'],
    partner: 'Dell Technologies'
  },
  {
    id: '202502009',
    title: 'Avaliação de Simulação de CFD com aplicação aeronáutica',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SIMULACAO,
    thumbnailUrl: 'https://www3.al.sp.gov.br/repositorio/noticia/N-08-2025/fg351160.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1401', name: 'Lourenço Junqueira Franco Meirelles', role: 'Engenharia Mecânica' },
      { id: '1419', name: 'Melina Belli Stergiou', role: 'Engenharia Mecânica' },
      { id: '1410', name: 'Luis Filippe Silva Gomes', role: 'Engenharia Mecânica' },
      { id: '1375', name: 'Gustavo Colombi Ribolla', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Paulo Roberto Bufacchi Mendes',
    longDescription: 'Validação e otimização de simulações CFD para prever fenômenos aerodinâmicos críticos em regimes transônicos, comparando malhas computacionais com dados experimentais de túnel de vento.',
    tags: ['NumericalSimulation','Aerodynamics'],
    partner: 'Embraer'
  },
  {
    id: '202502010',
    title: 'Generation of Puzzles For Logic Game',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://play-lh.googleusercontent.com/nhx3GgJLnv20HowhHNRjWhbmoqWIYkvfKaH850GyCColpRmy_du73HrIfBFSx18X1Q=w3840-h2160-rw',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1418', name: 'Mateus Moreira Pereira', role: 'Ciência da Computação' },
      { id: '1433', name: 'Raul Rangel Moraes Bezerra', role: 'Engenharia de Computação' },
      { id: '1447', name: 'Yan Vieira Romano', role: 'Engenharia de Computação' },                 
    ],
    advisor: 'Luciano Pereira Soares',
    longDescription: 'Desenvolvimento de um gerador de puzzles Nonogram que utiliza IA generativa para criar arte e um solver que emula o raciocínio humano para garantir a jogabilidade e fornecer dicas intuitivas.',
    tags: ['GenerativeAI','LogicPuzzles', 'ProceduralGeneration'],
    partner: 'Fanatee'
  },
  {
    id: '202502011',
    title: 'Triagem e Otimização do Check-up',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://hospitalsiriolibanes.org.br/sites/institucional/files/2025-12/interna_belavista-1.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1431', name: 'Rafaela Afferri de Oliveira', role: 'Ciência da Computação' },
      { id: '1429', name: 'Rafael Dourado Bastos de Oliveira', role: 'Engenharia de Computação' },
      { id: '1347', name: 'Beatriz Rodrigues de Freitas', role: 'Engenharia de Computação' },
      { id: '1396', name: 'Laura Pontiroli Machado', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Tiago Fernandes Tavares',
    longDescription: 'Implementação de um chatbot de triagem e análise de dados para identificar queixas de pacientes no pré-atendimento, otimizando o encaminhamento médico e a conversão de serviços hospitalares.',
    tags: ['HealthTech','Chatbot','HospitalManagement','PatientExperience'],
    partner: 'Hospital Sírio-Libanês'
  },
  {
    id: '202502012',
    title: 'Combate à Pirataria de Cartuchos HP no Mercado Livre',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://logosmarcas.net/wp-content/uploads/2020/12/Hewlett-Packard-Logo-2008-2014.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1343', name: 'Andre Pereira de Oliveira', role: 'Ciência da Computação' },
      { id: '1430', name: 'Rafael Gordon Paves', role: 'Engenharia de Computação' },
      { id: '1411', name: 'Luiz Eduardo Herreros Pini', role: 'Engenharia de Computação' },
      { id: '1394', name: 'Julia Almeida Silva', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Humberto Rodrigo Sandmann',
    longDescription: 'Desenvolvimento de uma plataforma automatizada de triagem e priorização de anúncios fraudulentos no Mercado Livre para otimizar o combate à pirataria de suprimentos HP.',
    tags: ['Dashboard','WebScraping','MarketplaceMonitoring'],
    partner: 'HP'
  },
  {
    id: '202502013',
    title: 'Aprimorando Modelos de Elevação para construir cidades mais resilientes',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://yt3.googleusercontent.com/3PfQYVO7HASuprs_eU-ZOcOAkmrRGCiUWzmJ5-AntxnFYEc71k2ZLsgnySO8bP3JoWDcEnFkCuQ=s900-c-k-c0x00ffffff-no-rj',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1376', name: 'Gustavo de Lorenzi Cancellier Katz', role: 'Engenharia Mecatrônica' },
      { id: '1387', name: 'Isabella Leão Pereira Lima', role: 'Engenharia Mecatrônica' },
      { id: '1215', name: 'Ana Beatriz Parra Ferreira', role: 'Engenharia Mecatrônica' },
      { id: '20610251', name: 'Rodrigo Bandeira Villela', role: 'Engenharia Mecânica' },                   
    ],
    advisor: 'Victor Antonio Seixas de Menezes Paiva',
    longDescription: 'Desenvolvimento de algoritmos de visão computacional e ciência de dados para refinar modelos de elevação gratuitos, removendo ruídos e aumentando a resolução para simulações precisas de inundações urbanas.',
    tags: ['UrbanResilience','ComputerVision'],
    partner: 'IPT'
  },
  {
    id: '202502014',
    title: 'Web Client for Port Video Monitoring with Defense AI',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://backend.intelbras.com/sites/default/files/2026-02/logo-intelbras-novo.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1425', name: 'Pedro de Lucca Sartori Chagas Ferro', role: 'Engenharia de Computação' },
      { id: '1359', name: 'David Matheus Conselvan', role: 'Engenharia de Computação' },
      { id: '1368', name: 'Fernando Alzueta', role: 'Engenharia de Computação' },
      { id: '1412', name: 'Luiza Ferreira Ehrenberger', role: 'Engenharia de Computação' },                   
    ],
    advisor: 'Marcel Parolin Jackowski',
    longDescription: 'Desenvolvimento de um cliente web moderno e seguro para monitoramento portuário, integrando sistemas de segurança inteligente e conversão de vídeo em tempo real para maior acessibilidade e conformidade.',
    tags: ['WebDevelopment','FullStack', 'VideoMonitoring','Cybersecurity'],
    partner: 'Intelbras'
  },
  {
    id: '202502015',
    title: 'Desenvolvimento de bancada de testes de resistência à água em produtos do setor agroindustrial',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://www.jassy.ag/wp-content/uploads/2019/08/Entrada_J.Assy_010819-1024x958.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1349', name: 'Breno Brolacci Schiavon', role: 'Engenharia Mecânica' },
      { id: '1225', name: 'Maia Fleider', role: 'Engenharia Mecatrônica' },
      { id: '1223', name: 'Leandra Ferreira Fontes', role: 'Engenharia Mecatrônica' },
      { id: '1416', name: 'Mariana Ribeiro Sávio', role: 'Engenharia Mecatrônica' },                   
    ],
    advisor: 'Fabio Ferraz Junior',
    longDescription: 'Desenvolvimento de uma bancada automatizada com CLP para testes de resistência à água e estanqueidade de componentes agroindustriais, seguindo normas internacionais de proteção.',
    tags: ['AgroTech','Estanqueidade','AutomacaoIndustrial','Sustainability'],
    partner: 'J.ASSY'
  },
  {
    id: '202502016',
    title: 'Protótipo de Validação Automatizada de Dados de Consumo de Energia com IA para Sustentabilidade',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://cdn.motor1.com/images/mgl/xWk8k/s1/mercedes-benz-social-distancing-logo.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1372', name: 'Giúlia Gomes Vallente', role: 'Ciência da Computação' },
      { id: '1357', name: 'Daniel da Rocha Prado', role: 'Ciência da Computação' },
      { id: '1348', name: 'Beni Sliozbergas', role: 'Ciência da Computação' },
      { id: '1341', name: 'Ana Helena Caiafa', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Graziela Simone Tonin',
    longDescription: 'Implementação de um pipeline automatizado com IA e OCR para validar dados de consumo de energia e combustíveis, garantindo a integridade dos relatórios de emissões (ESG) da Mercedes-Benz.',
    tags: ['Sustainability','ESG'],
    partner: 'Mercedes-Benz'
  },
  {
    id: '202502017',
    title: 'Driving Behaviour de Condutores via Machine Learning',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://cms-gazzconecta.s3.amazonaws.com/gazzconecta/2020/07/31173437/Mottu-Stock-20-07-28-2067.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1374', name: 'Gustavo Barroso Souza Cruz', role: 'Ciência da Computação' },
      { id: '1442', name: 'Thiago Penha Pinheiro da Costa', role: ' Ciência da Computação' },
      { id: '1353', name: 'Caio Frigerio Liberal', role: 'Ciência da Computação' }                 
    ],
    advisor: 'Marcio Fernando Stabile Junior',
    longDescription: 'Desenvolvimento de modelos de Machine Learning para classificar perfis de condutores e prever riscos operacionais com base em padrões de uso e telemetria da frota.',
    tags: ['DrivingBehaviour','MachineLearning','DataScience'],
    partner: 'Mottu'
  },
  {
    id: '202502018',
    title: 'Inteligência Artificial na Manutenção Preditiva: Detecção de Anomalias Multivariáveis com Machine Learning',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://rockwellautomation.scene7.com/is/image/rockwellautomation/OurCompany-1.3840.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1218', name: 'Cleilton Sousa Serra', role: 'Engenharia Mecatrônica' },
      { id: '1446', name: 'Vinícius Garcia Lopes', role: 'Engenharia Mecatrônica' },
      { id: '1074', name: 'Natan Kron Goldenberg Lewi', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Carlos Magno de Oliveira Valente',
    longDescription: 'Desenvolvimento de uma solução de IA para detecção de anomalias multivariáveis e classificação automática de falhas industriais, integrada à plataforma FactoryTalk para manutenção preditiva em tempo real.',
    tags: ['MachineLearning','IIoT', 'PredictiveMaintenance'],
    partner: 'Rockwell Automation'
  },
  {
    id: '202502019',
    title: 'Exams PDF reader/converter',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://ifs-p-001.sitecorecontenthub.cloud/api/public/content/new_size_948-711_ifs_tata_consultancy_services_logo_july_2022_670x300.jpg-273f76?v=676a79ee',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1214', name: 'Victor Pacheco dos Santos', role: 'Engenharia Mecânica' },
      { id: '1207', name: 'Guilherme da Franca Silva Escobar', role: 'Engenharia Mecânica' },
      { id: '1045', name: 'Guilherme Caproni de Faria', role: 'Engenharia de Computação' },                   
    ],
    advisor: 'Diego Pavan Soler',
    longDescription: 'Desenvolvimento de um sistema inteligente capaz de ler e extrair dados de exames médicos em PDF (digitais ou manuscritos) para integração automatizada em sistemas ERP.',
    tags: ['ComputerVision','HealthTech','DataScience'],
    partner: 'Tata Consultancy Services'
  },
  {
    id: '202502020',
    title: 'Control of medicine stock in hospitals and clinics',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://ifs-p-001.sitecorecontenthub.cloud/api/public/content/new_size_948-711_ifs_tata_consultancy_services_logo_july_2022_670x300.jpg-273f76?v=676a79ee',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1381', name: 'Henrique Manequini Rocha Pinto', role: 'Engenharia Mecatrônica' },
      { id: '1421', name: 'Nina Savoy de Sa', role: 'Ciência da Computação' },
      { id: '1385', name: 'Ian Cordibello Desponds', role: 'Ciência da Computação' },
      { id: '1221', name: 'Giselle Vieira de Melo', role: 'Engenharia Mecatrônica' },                   
      { id: '1378', name: 'Gustavo Rollo Dias Paulino', role: 'Engenharia Mecatrônica' },                   

    ],
    advisor: 'Alex Camilli Bottene',
    longDescription: 'Implementação de um sistema inteligente de controle de estoque para hospitais, focado na previsão de demanda e otimização da distribuição para eliminar desperdícios e garantir a disponibilidade de medicamentos.',
    tags: ['SupplyChain','InventoryOptimization','HospitalManagement',],
    partner: 'Tata Consultancy Services'
  },
  {
    id: '202502021',
    title: 'Chatbot Para Primeiro Atendimento',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://braziljournal.com/wp-content/uploads/2023/09/Weg2.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1366', name: 'Felipe Affonso Ribeiro de Maia', role: 'Engenharia de Computação' },
      { id: '1402', name: 'Luca Caruso', role: 'Engenharia de Computação' },
      { id: '1361', name: 'Eduardo Selber Castanho', role: 'Engenharia de Computação' },
      { id: '1380', name: 'Henrique Fazzio Badin', role: 'Engenharia de Computação' },                   
    ],
    advisor: 'Fabio Roberto de Miranda',
    longDescription: 'Desenvolvimento de um chatbot baseado em RAG para a WEG, capaz de realizar triagem técnica e responder dúvidas de colaboradores via Microsoft Teams, otimizando o fluxo de chamados internos.',
    tags: ['Chatbot','RAG','GenerativeAI','Industry40'],
    partner: 'WEG'
  },
  {
    id: '202502022',
    title: 'Sistema de Inteligência Artificial para Monitoramento Preditivo de Processos Industriais',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://braziljournal.com/wp-content/uploads/2023/09/Weg2.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1377', name: 'Gustavo Morin de Sousa', role: 'Engenharia Mecatrônica' },
      { id: '1389', name: 'João Antônio Gomes Garcia', role: 'Engenharia de Computação' },
      { id: '1397', name: 'Layne Pereira da Silva', role: 'Engenharia Mecatrônica' },
      { id: '1373', name: 'Guilherme Katayama Kaidei', role: 'Ciência da Computação' },
      { id: '1356', name: 'Carol Magario de Mattos Barretto', role: 'Engenharia Mecatrônica' },                   
    ],
    advisor: 'Lie Pablo Grala Pinto',
    longDescription: 'Desenvolvimento de um sistema de IA para monitoramento em tempo real de redes IIoT, focado na detecção de anomalias e previsão de falhas com alta precisão para evitar paradas produtivas.',
    tags: ['Industry40','IIoT','PredictiveMaintenance','MachineLearning',],
    partner: 'WEG'
  },
  {
    id: '2025010001',
    title: 'Sistema Computadorizado de Auxílio ao Diagnóstico de Câncer em Patologia Digital',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://accamargo.org.br/sites/default/files/styles/imagem_redonda_home/public/location/2024/07/itaim-fachada-red.jpg?h=8df58ce1&itok=-NnmUa1I',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1177', name: 'Diogo Pereira Lobo', role: 'Engenharia de Computação' },
      { id: '1199', name: 'Tales Ivalque Taveira de Freitas', role: 'Engenharia de Computação' },
      { id: '1175', name: 'Bruno Marques Li Volsi Falcao', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabio Jose Ayres',
    longDescription: 'Desenvolvimento de um sistema CAD que utiliza o modelo de fundação CHIEF para analisar lâminas digitais, fornecendo aos patologistas estimativas automatizadas da presença de câncer para auxiliar no diagnóstico.',
    tags: ['DigitalPathology','ComputerAidedDiagnosis','CAD','DeepLearning','HealthTech'],
    partner: 'A.C. Camargo'
  },
  {
    id: '2025010002',
    title: 'Desenvolvimento de um aparelho capaz de isolar e linearizar uma molécula única de DNA para estudo de biomarcadores no tratamento do câncer',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.BIOENGENHARIA,
    thumbnailUrl: 'https://d2yghbees9788u.cloudfront.net/saudebusiness/2025/07/shutterstock_2263273389-scaled.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1090', name: 'João Pedro Reis Lima', role: 'Engenharia Mecatrônica' },
      { id: '1073', name: 'Maria Eduarda Matta Mercer Mourao', role: 'Engenharia Mecânica' },
      { id: '1191', name: 'Nicolas Enzo Yassuda', role: 'Engenharia de Computação' },
      { id: '1077', name: 'Camila Bernardi Moniz', role: 'Engenharia Mecatrônica' },    
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Desenvolvimento de um equipamento de alta precisão para isolar e estirar moléculas individuais de DNA (DNA combing), permitindo a visualização de lacunas na fita simples e o estudo de mecanismos de resistência a quimioterápicos.',
    tags: ['LabEquipment','Biotec','DNACombing','',''],
    partner: 'A.C. Camargo'
  },
  {
    id: '2025010003',
    title: 'Desenvolvimento de algoritmos de análise de vídeo para interface com sistema de controle industrial',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://smetal.org.br/wp-content/uploads/2021/11/H105740-F00000-J007-630x420.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1079', name: 'Diego Baptista Daurea Machado', role: 'Engenharia Mecatrônica' },
      { id: '1178', name: 'Douglas Pablo Bracale Celestino', role: 'Engenharia de Computação' },
      { id: '1183', name: 'Gustavo Mendes da Silva', role: 'Engenharia de Computação' },
      { id: '1100', name: 'Pedro Ivo de Rizzo', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Carlos Magno de Oliveira Valente',
    longDescription: 'Desenvolvimento de algoritmos de visão computacional aplicados à automação industrial para integração com sistemas de controle distribuído (DCS), visando demonstrações tecnológicas e inovação em processos produtivos.',
    tags: ['IndustrialAutomation','ComputerVision','DCS','Industry40','SmartManufacturing'],
    partner: 'ABB'
  },
  {
    id: '2025010004',
    title: 'Sistema de localização de carrinhos de supermercado',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://media.licdn.com/dms/image/v2/D4D0BAQG89u7a-qc-mg/company-logo_200_200/B4DZUl2CxbHkAI-/0/1740096679438/airis_tecnologia_logo?e=1778112000&v=beta&t=CxWB886z4esYN8cf0JN8YoJL8Ecz3iqnx5mlrw4K9ZY',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1173', name: 'Arthur Moreira Tamm', role: 'Engenharia de Computação' },
      { id: '1098', name: 'Pedro Deslandes Castanheira Hun', role: 'Engenharia Mecatrônica' },
      { id: '1043', name: 'Felipe Menotti Trintim', role: 'Engenharia de Computação' },
      { id: '1172', name: 'Ariel Tamezgui Leventhal', role: 'Engenharia de Computação' },
    ],
    advisor: 'Silvio Szafir',
    longDescription: 'Implementação de um sistema de localização em tempo real (RTLS) utilizando tecnologia Ultra-Wideband (UWB) e processamento em borda para rastreio preciso de carrinhos inteligentes em ambientes indoor.',
    tags: ['IndoorPositioning','IoT','UWB','NVIDIAJetson','HardwareIntegration'],
    partner: 'Airis Tecnologia'
  },
  {
    id: '2025010005',
    title: 'Soluções IoT para Processamento de Sinais de Sensores de Vibração',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://d3h1nu1oevgs78.cloudfront.net/posts/-380400.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1205', name: 'Francisco Luiz Pereira da Silva', role: 'Engenharia Mecânica' },
      { id: '1103', name: 'Rodrigo Camargo Gomes', role: 'Engenharia Mecatrônica' },
      { id: '1219', name: 'Eduardo Heitor Penteado de Mello Peixoto', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Lie Pablo Grala Pinto',
    longDescription: 'Desenvolvimento de algoritmos para processamento local de sinais de vibração em dispositivos IoT, permitindo a detecção de falhas na borda (edge) para reduzir o consumo de energia e o tráfego de dados.',
    tags: ['IoT','Industry40','VibrationAnalysis','PredictiveMaintenance','EmbeddedSystems'],
    partner: 'Ambev'
  },
  {
    id: '2025010006',
    title: 'Energy Asset Grid Integration',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://play-lh.googleusercontent.com/fP2wyT-MmhqYChvbykVtOrIxdYMWHrYZJX2kE4bFD373e7rufv8lnAxFFwHrRNu_Hm5z',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1032', name: 'Arthur Boschini da Fonseca', role: 'Engenharia de Computação' },
      { id: '1050', name: 'Joseph Kallas Neto', role: 'Engenharia de Computação' },
      { id: '1211', name: 'Pedro Ribeiro Lodi', role: 'Engenharia Mecânica' },
      { id: '1039', name: 'Dom Ruan Suzano Figueira da Silva', role: 'Engenharia de Computação' },
    ],
    advisor: 'Raul Ikeda Gomes da Silva',
    longDescription: 'Integração de sistemas via API para criar uma Usina Virtual (VPP), permitindo o controle automatizado de dispositivos de climatização para reduzir a carga na rede elétrica durante picos de demanda e diminuir a dependência de combustíveis fósseis.',
    tags: ['VirtualPowerPlant','EnergyManagement','SmartGrid','IoT','EnergyEfficiency'],
    partner: 'Boldr'
  },
  {
    id: '2025010007',
    title: 'Desenvolvimento de um kit de acoplamento para unir um patinete elétrico a uma cadeira de rodas',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://i0.statig.com.br/bancodeimagens/cn/72/vp/cn72vpkkg5u62v6izzjsr3aij.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1208', name: 'Matheus de Freitas Souza', role: 'Engenharia Mecânica' },
      { id: '1201', name: 'Bruno Conte Paiva', role: 'Engenharia Mecânica' },
      { id: '1209', name: 'Matheus Lopes Vilar', role: 'Engenharia Mecânica' },
      { id: '1207', name: 'Guilherme da Franca Silva Escobar', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Victor Antonio Seixas de Menezes Paiva',
    longDescription: 'Desenvolvimento do KOM-BEE, um triciclo elétrico modular projetado para transporte de passageiros, logística de última milha e coleta seletiva, incluindo soluções de acoplamento para acessibilidade.',
    tags: ['ElectricVehicle','Micromobility','Accessibility','MechanicalEngineering','ProductDesign'],
    partner: 'Cicloway'
  },
  {
    id: '2025010008',
    title: 'RISC-V para Uso Aeroespacial',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://portal-adm.campinas.sp.gov.br/sites/default/files/noticias/img-avulsa/cti%20renato%20archer.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1192', name: 'Pedro Balbo Portella', role: 'Engenharia de Computação' },
      { id: '1035', name: 'Caio Bertolani Travain', role: 'Engenharia de Computação' },
      { id: '1193', name: 'Pedro Cliquet do Amaral', role: 'Engenharia de Computação' },
      { id: '1058', name: 'Pedro Paulo Moreno Camargo', role: 'Engenharia de Computação' },
      { id: '1108', name: 'Jadon Dewey', role: 'Engenharia Elétrica, Texas A&M University' },
      { id: '1107', name: 'Eddie Villegas', role: 'Engenharia Elétrica, Texas A&M University' },

    ],
    advisor: 'Rafael Corsi Ferrão',
    longDescription: 'Exploração e aprimoramento da arquitetura RISC-V para aplicações aeroespaciais, visando o desenvolvimento de sistemas tolerantes a falhas e a criação de um chip (ASIC) nacional para uso governamental.',
    tags: ['RISCV','Aerospace','EmbeddedSystems','ComputerArchitecture','FaultTolerance'],
    partner: 'CTI Renato Archer'
  },
  {
    id: '2025010009',
    title: 'Guardrails em IA Generativa',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://uploads.startups.com.br/2025/07/oxygea-20-950x553.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1198', name: 'Rodrigo Paoliello de Medeiros', role: 'Engenharia de Computação' },
      { id: '1181', name: 'Gabriel Mendonça de Mello Hermida', role: 'Engenharia de Computação' },
      { id: '1180', name: 'Fernanda de Oliveira Pereira', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabricio Jailson Barth',
    longDescription: 'Implementação de uma arquitetura modular de segurança (guardrails) para IA Generativa, capaz de filtrar toxicidade, evitar alucinações e proteger contra vazamento de dados e ataques de jailbreak em assistentes virtuais.',
    tags: ['GenerativeAI','Guardrails','LLM','PromptEngineering','ArtificialIntelligence'],
    partner: 'Dell Technologies'
  },
  {
    id: '2025010010',
    title: 'Implementação de Navegação Autônoma em Veículo Terrestre: Aprimoramento e Testes',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://assets.revistacultivar.com.br/bf11d358-7135-4036-868f-08ebba90470c.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1222', name: 'Guilherme Garrido Klingelfus Pinheiro', role: 'Engenharia Mecatrônica' },
      { id: '1212', name: 'Rafael Pacheco Paolino', role: 'Engenharia Mecânica' },
      { id: '1190', name: 'Matheus Ribeiro Barros', role: 'Engenharia de Computação' },
      { id: '1174', name: 'Bruna Lima Meinberg', role: 'Engenharia de Computação' },
    ],
    advisor: 'Vinicius Licks',
    longDescription: 'Aprimoramento físico e lógico de um robô autônomo para monitoramento agrícola, focando na otimização da locomoção e na precisão dos algoritmos de navegação em terrenos irregulares.',
    tags: ['AutonomousNavigation','AgroTech','Robotics','MechanicalOptimization','PrecisionAgriculture'],
    partner: 'Embrapa'
  },
  {
    id: '2025010011',
    title: 'Seleção Inteligente de Minigames para o Jogo Arena of Dreams',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://play-lh.googleusercontent.com/A4wtoDzw2Gt0ZB1VEyR9acHpd3jRxzljCbfLPuoFQMsmwQl9MrAlCIZxx-40gY4zag',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '591', name: 'Luca Cazzolato Machado', role: 'Engenharia de Computação' },
      { id: '1196', name: 'Pedro Henrique Rizo Colpas', role: 'Engenharia de Computação' },
      { id: '1194', name: 'Pedro Fracassi', role: 'Engenharia de Computação' },
    ],
    advisor: 'Tiago Sanches da Silva',
    longDescription: 'Substituição de sistemas aleatórios por um algoritmo de seleção inteligente em jogos mobile, utilizando embeddings multidimensionais para reduzir a percepção de repetitividade e aumentar o engajamento dos jogadores.',
    tags: ['GameDesign','ComputerVision','Embeddings','UserExperience','MobileGaming'],
    partner: 'Fanatee'
  },
  {
    id: '2025010012',
    title: 'Impressão de Peças em Resina',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://fiberbus.com.br/images/services/pintura/pintura_g.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1214', name: 'Victor Pacheco dos Santos', role: 'Engenharia Mecânica' },
      { id: '1095', name: 'Luca Oshiro Camargo', role: 'Engenharia Mecatrônica' },
      { id: '1213', name: 'Rodrigo Bandeira Villela', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Gustavo Pollettini Marcos',
    longDescription: '',
    tags: ['3DPrinting','AdditiveManufacturing','ResinPrinting','IndustrialDesign','MechanicalTesting'],
    partner: 'Estudo comparativo de tecnologias de impressão 3D (DLP e PolyJet) e usinagem CNC utilizando resinas de alto desempenho para a produção de coberturas de mecanismos de portas, com foco em acabamento estético e resistência mecânica.'
  },
  {
    id: '2025010013',
    title: '123Ask',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://s2-oglobo.glbimg.com/4p69yjqFJ5Oe04CeJLLjE5Gx3EQ=/0x0:1314x880/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2024/A/m/KPaB3xTAeSSBYS4N7Hrw/fintalk.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1169', name: 'Alberto Mansur', role: 'Engenharia de Computação' },
      { id: '1186', name: 'Kevin Nagayuki Shinohara', role: 'Engenharia de Computação' },
      { id: '1045', name: 'Guilherme Caproni de Faria', role: 'Engenharia de Computação' },
      { id: '1038', name: 'Caroline Chaim de Lima Carneiro', role: 'Engenharia de Computação' },
    ],
    advisor: 'Tiago Fernandes Tavares',
    longDescription: 'Desenvolvimento de um sistema de tradução de linguagem natural para SQL (Text-to-SQL) utilizando LLMs, permitindo que usuários realizem consultas complexas em bancos de dados dinâmicos através de perguntas simples.',
    tags: ['TextToSQL','NaturalLanguageProcessing','GenerativeAI','BusinessIntelligence','SoftwareArchitecture'],
    partner: 'Fintalk'
  },
  {
    id: '2025010014',
    title: 'Aplicação web para monitoramento de feedbacks de usuários, integrada a um aplicativo voltado à democratização de línguas indígenas',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://img.odcdn.com.br/wp-content/uploads/2021/06/shutterstock_157995017_Easy-Resize.com_-e1623963097228.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1184', name: 'Isabella dos Santos de Amorim', role: 'Engenharia de Computação' },
      { id: '1171', name: 'Ana Laiz Novais de Farias', role: 'Engenharia de Computação' },
      { id: '1044', name: 'Giovana Cassoni Andrade', role: 'Engenharia de Computação' },
      { id: '1229', name: 'Samuel Koch', role: 'Engenharia Elétrica, Texas A&M University' },
      { id: '1230', name: 'Nicholas Petersilge', role: 'Engenharia Elétrica, Texas A&M University' },
    ],
    advisor: 'Graziela Simone Tonin',
    longDescription: 'Desenvolvimento de uma plataforma web de monitoramento e integração de coleta de feedbacks em um aplicativo de tradução, visando o aprimoramento de modelos de IA para a preservação da língua indígena Nheengatu.',
    tags: ['IndigenousLanguages','WebDevelopment','UserFeedback','SocialImpact','LanguageModel'],
    partner: 'IBM Brasil'
  },
  {
    id: '2025010015',
    title: 'Automação de Bancada de Testes para Sensores de Fluxo Implementados em Cultivadoras',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://sejatrainee.com.br/wp-content/uploads/2024/11/Capas-artigos_20241122_153034_0000.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1226', name: 'Ralph Michaan', role: 'Engenharia Mecatrônica' },
      { id: '1216', name: 'Augusto Monteiro Giuliani', role: 'Engenharia Mecatrônica' },
      { id: '1228', name: 'Taina Pereira de Bonfim', role: 'Engenharia Mecatrônica' },
      { id: '1217', name: 'Bruno Olivares Sanchez', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Fabio Ferraz Junior',
    longDescription: 'Automação de uma bancada de testes hidráulica para sensores de fluxo agrícola, utilizando CLP e interface LabVIEW para garantir a precisão, rastreabilidade e eficiência na detecção de obstruções em sistemas de plantio.',
    tags: ['IndustrialAutomation','PLC','LadderLogic','AgroTech','TestBench'],
    partner: 'J. ASSY'
  },
  {
    id: '2025010016',
    title: 'Automatização do controle de movimentação de localização de obras do acervo do MASP',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO, 
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/MASP_Brazil.jpg/1280px-MASP_Brazil.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1195', name: 'Pedro Gomes de Sá Drumond', role: 'Engenharia de Computação' },
      { id: '1170', name: 'Alexandre Rodrigues Santarossa', role: 'Engenharia de Computação' },
      { id: '1074', name: 'Natan Kron Goldenberg Lewi', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Luiz Fernando Cardoso dos Santos Durão',
    longDescription: 'Desenvolvimento de um sistema de automação e rastreamento de obras de arte via QR Code integrado ao sistema de gestão do MASP, visando eliminar erros manuais e otimizar a segurança na movimentação do acervo.',
    tags: ['InformationSystems','InventoryManagement','AssetTracking','MuseumTech','Logistics'],
    partner: 'MASP'
  },
  {
    id: '2025010017',
    title: 'Utilização de compósitos no mercado automotivo pesado e agrícola',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.ADMINISTRACAO,
    thumbnailUrl: 'https://l3.com.br/wp-content/uploads/2022/11/Foto_Iochpe.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1210', name: 'Pedro Henrique Cardoso Peretto', role: 'Engenharia Mecânica' },
      { id: '1206', name: 'Guido Lacerda Soares do Couto Rosa', role: 'Engenharia Mecânica' },
      { id: '1220', name: 'Enzo Martins Barroso del Manto', role: 'Engenharia Mecatrônica' },
      { id: '1202', name: 'Eduardo Antoniazzi Zetone', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Israel Ferreira Alves',
    longDescription: 'Estudo de viabilidade técnica e comercial para a aplicação de materiais compósitos em veículos pesados e agrícolas, incluindo dimensionamento de mercado e o desenvolvimento de uma ferramenta para seleção de processos de fabricação.',
    tags: ['MarketAnalysis','AutomotiveIndustry','AgroTech','MaterialSubstitution','ManufacturingProcesses'],
    partner: 'Maxion Structural Components'
  },
  {
    id: '2025010018',
    title: 'Otimizando o Abastecimento de Estoque por meio de Inteligência Computacional',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://mevo.com.br/share.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1036', name: 'Caio de Camargo Aranha Tieri', role: 'Engenharia de Computação' },
      { id: '856', name: 'Pedro Osborn Mahfuz', role: 'Engenharia de Computação' },
      { id: '1187', name: 'Luana Wilner Abramoff', role: 'Engenharia de Computação' },
      { id: '1063', name: 'Thomas Cavalcanti Chabro', role: 'Engenharia de Computação' },
    ],
    advisor: 'Rodolfo da Silva Avelino',
    longDescription: 'Desenvolvimento de um sistema de inteligência computacional e API de suporte à decisão para otimizar o abastecimento de estoque da Mevo, gerando recomendações de compra baseadas em dados históricos e restrições de inventário.',
    tags: ['DataScience','DataDriven','StockOptimization','HealthTech','InventoryManagement'],
    partner: ''
  },
  {
    id: '2025010019',
    title: 'Negociação entre agentes de IA Generativa para comunicação em Spatial Web',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://itforum.com.br/wp-content/uploads/2023/09/NTT-Data-adquire-Conexos.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1189', name: 'Matheus Raffaelle Nery Castellucci', role: 'Engenharia de Computação' },
      { id: '1182', name: 'Gustavo Eliziario Stevenson de Oliveira', role: 'Engenharia de Computação' },
      { id: '1176', name: 'Caio Ortega Bôa', role: 'Engenharia de Computação' },
      { id: '1185', name: 'João Pedro Rodrigues dos Santos', role: 'Engenharia de Computação' },
    ],
    advisor: 'Luciano Pereira Soares',
    longDescription: 'Desenvolvimento de um sistema de agentes autônomos de IA Generativa dotados de memória computacional, capazes de navegar, interagir e negociar de forma independente entre si dentro de um ambiente virtual 3D.',
    tags: ['GenerativeAI','LLM','MultiAgentSystems','VirtualEnvironments','AutonomousAgents'],
    partner: 'NTT Data Brasil'
  },
  {
    id: '2025010020',
    title: 'Estudo de plantabilidade e sujidade na produção de sementes de milho',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.ADMINISTRACAO,
    thumbnailUrl: 'https://www.syngenta.com.br/sites/g/files/kgtney466/files/styles/v2_image_default/public/media/image/2025/12/04/syngenta_logo.jpg?itok=YnnimrBh',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1204', name: 'Filippo Ferraro', role: 'Engenharia Mecânica' },
      { id: '1200', name: 'Alfredo Montingelli Villela', role: 'Engenharia Mecânica' },
      { id: '1203', name: 'Fernando Campos Kaizer', role: 'Engenharia Mecânica' },
      { id: '1224', name: 'Luiz Gustavo Strenger Domingues de Castro Reis', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Aplicação da metodologia DMAIC no processo de beneficiamento de sementes da Syngenta para otimizar os protocolos de amostragem e inspeção, mitigando falhas de sujidade e plantabilidade antes da distribuição ao cliente final.',
    tags: ['QualityControl','ProcessEngineering','AgroTech','ContinuousImprovement','Agribusiness'],
    partner: 'Syngenta Seeds'
  },
  {
    id: '2025010021',
    title: 'Plataforma para Gerenciamento de Dados de Abastecimentos em Grandes Frotas',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://www.infomoney.com.br/wp-content/uploads/2024/07/versa-fuel-van.jpeg?quality=70',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1188', name: 'Luca Mizrahi', role: 'Engenharia de Computação' },
      { id: '1197', name: 'Pedro Toledo Piza Civita', role: 'Engenharia de Computação' },
      { id: '1086', name: 'Gabriel Barreto da Costa Barbosa', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Maciel Calebe Vidal',
    longDescription: 'Desenvolvimento de um dashboard gerencial em Power BI integrado ao BigQuery para automatizar a análise de dados de abastecimento de grandes frotas, eliminando planilhas manuais e fornecendo insights estratégicos para a Versa Fuel.',
    tags: ['BusinessIntelligence','DataVisualization','PowerBI','BigQuery','Dashboards'],
    partner: 'Versa Fuel'
  },
];
