
import { Project, ProjectCategory, AwardType } from './types';

export const COLORS = {
  PRIMARY: '#EF3340', // PANTONE 2034 C
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  TEAL: '#00AFAD',    // PANTONE 3258 C
  LIME: '#84BD00',    // PANTONE 7487 C
  YELLOW: '#FEDD00',  // PANTONE YELLOW C
  ORANGE: '#E89923',  // PANTONE 7411 C
  MAGENTA: '#DF1995', // PANTONE 218 C
  PURPLE: '#802FDE',  // PANTONE 2593 C
};

export const PARTNERS = [
  'A.C. Camargo','Airis Tecnologia','Akaer','Binario Cloud','Boldr','BYX','CTI Renato Archer','Dell Technologies', 'Embraer', 'Fanatee','Hospital Sírio-Libanês',
  'HP','IPT','Intelbras','J.ASSY','Mercedes-Benz','Mottu','Rockwell Automation','Tata Consultancy Services','WEG','ABB','Ambev','Cicloway',
  'Embrapa','Fiberbus','Fintalk','IBM Brasil','MASP','Maxion Structural Components','NTT Data Brasil','Mevo','Syngenta Seeds','Versa Fuel', 
  'Alupar','B3', 'Braskem','DAO Capital','Legacy Capital','Nvidia','Pinpag','Tivit','',
].sort();

export const MOCK_PROJECTS: Project[] = [
  {
    id: '202502001',
    title: 'Impressão 3D de estabilizador bucal para radioterapia',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.BIOENGENHARIA,
    thumbnailUrl: 'https://accamargo.org.br/sites/default/files/styles/imagem_redonda_home/public/location/2020-08/unidades-pires.jpg?h=bc835eb6&itok=WxHi5Dlt',
    videoUrl: '',
    galleryUrls: [
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1351', name: 'Bruno Alencar Braghette', role: 'Engenharia Mecânica' },
      { id: '1422', name: 'Paulo Augusto dos Passos Oliveira', role: 'Engenharia Mecânica' },
      { id: '1358', name: 'Daniel Vergamini Luna Frussa', role: 'Engenharia Mecânica' },
      { id: '1437', name: 'Ruy de Paula Souza Neto', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Dispositivos como bolus e estabilizador bucal são utilizados durante a radioterapia para melhor eficácia do tratamento. O estabilizador bucal e o bolus (utilizado em outras áreas do corpo) são métodos pioneiros do A.C.Camargo que permitem um posicionamento adequado do paciente durante a sessão de radioterapia, o qual é essencial para garantir a precisão na entrega da dose de radiação ao tumor, minimizando danos aos tecidos saudáveis. O bolus e o estabilizador bucal garantem um posicionamento consistente em cada sessão e visam também o conforto do paciente. Esses materiais são produzidos na fase de planejamento do tratamento, com apoio de imagens como tomografias e ressonâncias, para definir o posicionamento ideal e a área exata a ser tratada e definindo o formato, molde e dimensões do bolus ou estabilizador. Após medições, a equipe segue para a confecção dos dispositivos que é feita de forma individual e artesanal. A equipe desprende algumas horas na confecção dos mesmos. Em resumo, o posicionamento do paciente influencia diretamente a eficácia e a segurança do tratamento, sendo essencial a colaboração entre o paciente, o oncologista e a equipe de radioterapia. Desta forma, o objetivo desta proposta seria customizar a confecção destes dispositivos. Nesta proposta teria a inclusão de pacientes com indicação de confecção do estabilizador bucal e bolus.',
    tags: ['3DPrinting','Bioengineering','PatientExperience'],
    partner: 'A.C. Camargo'
  },
  {
    id: '202502002',
    title: 'Mapeamento de produtos em supermercado',
    description: 'Criação de um sistema de mapeamento dinâmico e adaptativo que reconstrói a planta do supermercado e otimiza rotas com base na análise autônoma do fluxo e comportamento dos carrinhos de compras.',
    semester: '2',
    year: 2025,
    category: ProjectCategory.EMBARCADOS,
    thumbnailUrl: 'https://www.firenzetech.com.br/_next/static/media/heatmaps.37480021.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1342', name: 'Ananda Julia Galvão Campêlo', role: 'Engenharia de Computação' },
      { id: '1186', name: 'Kevin Nagayuki Shinohara', role: 'Engenharia de Computação' },
      { id: '591', name: 'Luca Cazzolato Machado', role: 'Engenharia de Computação' },      
      { id: '1441', name: 'Thiago Gonçalves Guadagnoli de Sousa', role: 'Engenharia de Computação' },      

    ],
    advisor: 'Vinicius Licks',
    longDescription: 'Criação de um sistema de mapeamento dinâmico e inteligente que reconstrói a planta de supermercados e otimiza rotas a partir do comportamento de fluxo dos carrinhos.',
    tags: ['ComputerVision', 'IoT', 'DataScience'],
    partner: 'Airis Tecnologia'
  },
  {
    id: '202502003',
    title: 'Desenvolvimento de Navegação Autônoma para VANT Utilizando Técnicas de Aprendizado por Reforço',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.ROBOTICA,
    thumbnailUrl: 'https://www.hitsvalenews.com.br/uploads/images/2024/08/akaer-tem-vagas-de-trabalho-abertas-em-sao-jose-dos-campos-1c19a.webp',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1384', name: 'Henrique Turco Gera', role: 'Ciência da Computação' },
      { id: '1408', name: 'Luigi Orlandi Quinze', role: 'Ciência da Computação' },
      { id: '1445', name: 'Victoria Leal Garcia de Souza', role: 'Engenharia Mecatrônica' },      
      { id: '1399', name: 'Leonardo Sterman Freitas', role: 'Ciência da Computação' },      

    ],
    advisor: 'Fabricio Jailson Barth',
    longDescription: 'Este projeto visa desenvolver, em simulação, um sistema de navegação para um VANT (Veículo Aéreo Não Tripulado) de asa fixa utilizando aprendizado por reforço. (Reinforcement Learning). O ambiente de treinamento foi implementado diretamente sobre a modelagem mecânica do VANT (Aerosonde), no referencial NED (North-East-Down), garantindo que a dinâmica (atuadores, restrições e equações de movimento) utilizada pelo VANT reflita seu comportamento físico. O veículo emprega Proximal Policy Optimization (PPO), adequado a espaços de ação contínuos (complexos) e estáveis para controle fino, aprendendo a minimizar distância ao alvo (waypoint), alinhar direção e respeitar os limites operacionais. Em paralelo, a modelagem mecânica foi consolidada (MATLAB) para validação e análise, enquanto o ambiente em Python (compatível com a biblioteca Gymnasium) integra o mesmo conjunto de equações ao loop de interação do aprendizado por reforço. Essa integração do modelo mecânico com o ambiente de Reinforcement Learning assegura consistência entre simulação física e aprendizado, favorecendo a transferência de resultados e a avaliação comparativa de algoritmos.',
    tags: ['DataScience', 'Simulation', 'ReinforcementLearning'],
    partner: 'Akaer'
  },
  {
    id: '202502004',
    title: 'Monitoramento de rede em máquinas virtuais em uma infraestrutura OpenStack Kolla-Ansible',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CLOUD_COMPUTING,
    thumbnailUrl: 'https://cdn.prod.website-files.com/643d2eea03135260bdaca209/6585cea39ae01230757b9f31_QuantumCloud.webp',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1432', name: 'Raphael Cavalcanti Banov', role: 'Engenharia de Computação' },
      { id: '1391', name: 'João Pedro Gardenal Sarti', role: 'Ciência da Computação' },
      { id: '1355', name: 'Carlos Eduardo Porciuncula Yamada', role: 'Engenharia de Computação' },            
    ],
    advisor: 'Tiago Augusto Orcajo Demay Cordeiro',
    longDescription: 'Desenvolvimento de uma ferramenta independente para monitoramento granular de tráfego em nuvem OpenStack, capaz de distinguir fluxos internos e externos para identificação proativa de anomalias.',
    tags: ['Cloud', 'OpenStack', 'Networking'],
    partner: 'Binario Cloud'
  },
  {
    id: '202502005',
    title: 'Widget Launchpad: Design, Build & Ship with Boldr',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://shopboldr.com/cdn/shop/files/App_Icon_Mockup_3.png?v=1726739516',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1403', name: 'Luca Santana Feltrin', role: 'Ciência da Computação' },
      { id: '1362', name: 'Eduardo Takei Yaginuma', role: 'Ciência da Computação' },
      { id: '1364', name: 'Esther Caroline Cunha Rodrigues', role: 'Ciência da Computação' },      
      { id: '1370', name: 'Gabriel Fernando Missaka Mendes', role: 'Ciência da Computação' },      

    ],
    advisor: 'Luiz Fernando Cardoso dos Santos Durão',
    longDescription: 'Desenvolvimento e lançamento de widgets mobile multiplataforma focados em design, vivenciando o ciclo completo de entrega de software e métricas de usuário em um ambiente real de startup.',
    tags: ['MobileDevelopment'],
    partner: 'Boldr'
  },
  {
    id: '202502006',
    title: 'Diagnóstico de Dados Aplicado ao Fluxo de Empréstimo Consignado Público',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://byx.com.br/cel-cartao.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1423', name: 'Pedro Antônio Braga Dutra', role: 'Engenharia de Computação' },
      { id: '1369', name: 'Fernando Pinheiro Silva Fernandes de Mattos', role: 'Engenharia de Computação' },
      { id: '1438', name: 'Sérgio Carmelo Torres Filho', role: 'Engenharia de Computação' },            
    ],
    advisor: 'Raul Ikeda Gomes da Silva',
    longDescription: 'Aplicação de diagnóstico de dados e inteligência analítica para identificar gargalos e aumentar a taxa de conversão na esteira de originação de crédito consignado.',
    tags: ['DataScience'],
    partner: 'BYX'
  },
  {
    id: '202502007',
    title: 'Otimização de uma CPU RISC-V',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.EMBARCADOS,
    thumbnailUrl: 'https://www.forumcampinas.org.br/interdependencia/wp-content/uploads/2023/11/CTI-2023-entrada.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1398', name: 'Leonardo Merlin Paloschi', role: 'Engenharia de Computação' },
      { id: '1427', name: 'Pedro Pereira Cecílio Ventura', role: 'Engenharia de Computação' },
      { id: '1405', name: 'Lucas Fernando de Souza Lima', role: 'Engenharia de Computação' },
      { id: '1386', name: 'Ilana Chaia Finger', role: 'Engenharia de Computação' },            
            
    ],
    advisor: 'Rafael Corsi Ferrão',
    longDescription: 'Otimização de hardware e software de uma CPU RISC-V em VHDL para aumentar o desempenho e a confiabilidade de sistemas de processamento em satélites.',
    tags: ['ComputerArchitecture','EmbeddedSystems'],
    partner: 'CTI Renato Archer'
  },
  {
    id: '202502008',
    title: 'Um framework para avaliação de Vision Language Models',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/34/RR1-_Dell_Campus.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1383', name: 'Henrique Scofield Sotto Mayor', role: 'Ciência da Computação' },
      { id: '1363', name: 'Ellen Coutinho Lião da Silva', role: 'Engenharia de Computação' },
      { id: '1227', name: 'Rodrigo Eiji Furukawa', role: 'Engenharia Mecatrônica' },
      { id: '1409', name: 'Luis Antonio Santana Rodrigues', role: 'Engenharia de Computação' },            
            
    ],
    advisor: 'Fabio Jose Ayres',
    longDescription: 'Desenvolvimento de um framework modular em Python para avaliação sistemática de modelos multimodais (VLMs) em tarefas de interpretação e resposta sobre conteúdos de vídeo.',
    tags: ['VLM','ComputerVision','DeepLearning'],
    partner: 'Dell Technologies'
  },
  {
    id: '202502009',
    title: 'Avaliação de Simulação de CFD com aplicação aeronáutica',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SIMULACAO,
    thumbnailUrl: 'https://www3.al.sp.gov.br/repositorio/noticia/N-08-2025/fg351160.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1401', name: 'Lourenço Junqueira Franco Meirelles', role: 'Engenharia Mecânica' },
      { id: '1419', name: 'Melina Belli Stergiou', role: 'Engenharia Mecânica' },
      { id: '1410', name: 'Luis Filippe Silva Gomes', role: 'Engenharia Mecânica' },
      { id: '1375', name: 'Gustavo Colombi Ribolla', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Paulo Roberto Bufacchi Mendes',
    longDescription: 'Validação e otimização de simulações CFD para prever fenômenos aerodinâmicos críticos em regimes transônicos, comparando malhas computacionais com dados experimentais de túnel de vento.',
    tags: ['NumericalSimulation','Aerodynamics'],
    partner: 'Embraer'
  },
  {
    id: '202502010',
    title: 'Generation of Puzzles For Logic Game',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://play-lh.googleusercontent.com/nhx3GgJLnv20HowhHNRjWhbmoqWIYkvfKaH850GyCColpRmy_du73HrIfBFSx18X1Q=w3840-h2160-rw',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1418', name: 'Mateus Moreira Pereira', role: 'Ciência da Computação' },
      { id: '1433', name: 'Raul Rangel Moraes Bezerra', role: 'Engenharia de Computação' },
      { id: '1447', name: 'Yan Vieira Romano', role: 'Engenharia de Computação' },                 
    ],
    advisor: 'Luciano Pereira Soares',
    longDescription: 'Desenvolvimento de um gerador de puzzles Nonogram que utiliza IA generativa para criar arte e um solver que emula o raciocínio humano para garantir a jogabilidade e fornecer dicas intuitivas.',
    tags: ['GenerativeAI','LogicPuzzles', 'ProceduralGeneration'],
    partner: 'Fanatee'
  },
  {
    id: '202502011',
    title: 'Triagem e Otimização do Check-up',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://hospitalsiriolibanes.org.br/sites/institucional/files/2025-12/interna_belavista-1.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1431', name: 'Rafaela Afferri de Oliveira', role: 'Ciência da Computação' },
      { id: '1429', name: 'Rafael Dourado Bastos de Oliveira', role: 'Engenharia de Computação' },
      { id: '1347', name: 'Beatriz Rodrigues de Freitas', role: 'Engenharia de Computação' },
      { id: '1396', name: 'Laura Pontiroli Machado', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Tiago Fernandes Tavares',
    longDescription: 'Implementação de um chatbot de triagem e análise de dados para identificar queixas de pacientes no pré-atendimento, otimizando o encaminhamento médico e a conversão de serviços hospitalares.',
    tags: ['HealthTech','Chatbot','HospitalManagement','PatientExperience'],
    partner: 'Hospital Sírio-Libanês'
  },
  {
    id: '202502012',
    title: 'Combate à Pirataria de Cartuchos HP no Mercado Livre',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://logosmarcas.net/wp-content/uploads/2020/12/Hewlett-Packard-Logo-2008-2014.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1343', name: 'Andre Pereira de Oliveira', role: 'Ciência da Computação' },
      { id: '1430', name: 'Rafael Gordon Paves', role: 'Engenharia de Computação' },
      { id: '1411', name: 'Luiz Eduardo Herreros Pini', role: 'Engenharia de Computação' },
      { id: '1394', name: 'Julia Almeida Silva', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Humberto Rodrigo Sandmann',
    longDescription: 'Desenvolvimento de uma plataforma automatizada de triagem e priorização de anúncios fraudulentos no Mercado Livre para otimizar o combate à pirataria de suprimentos HP.',
    tags: ['Dashboard','WebScraping','MarketplaceMonitoring'],
    partner: 'HP'
  },
  {
    id: '202502013',
    title: 'Aprimorando Modelos de Elevação para construir cidades mais resilientes',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://yt3.googleusercontent.com/3PfQYVO7HASuprs_eU-ZOcOAkmrRGCiUWzmJ5-AntxnFYEc71k2ZLsgnySO8bP3JoWDcEnFkCuQ=s900-c-k-c0x00ffffff-no-rj',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1376', name: 'Gustavo de Lorenzi Cancellier Katz', role: 'Engenharia Mecatrônica' },
      { id: '1387', name: 'Isabella Leão Pereira Lima', role: 'Engenharia Mecatrônica' },
      { id: '1215', name: 'Ana Beatriz Parra Ferreira', role: 'Engenharia Mecatrônica' },
      { id: '20610251', name: 'Rodrigo Bandeira Villela', role: 'Engenharia Mecânica' },                   
    ],
    advisor: 'Victor Antonio Seixas de Menezes Paiva',
    longDescription: 'Desenvolvimento de algoritmos de visão computacional e ciência de dados para refinar modelos de elevação gratuitos, removendo ruídos e aumentando a resolução para simulações precisas de inundações urbanas.',
    tags: ['UrbanResilience','ComputerVision'],
    partner: 'IPT'
  },
  {
    id: '202502014',
    title: 'Web Client for Port Video Monitoring with Defense AI',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://backend.intelbras.com/sites/default/files/2026-02/logo-intelbras-novo.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1425', name: 'Pedro de Lucca Sartori Chagas Ferro', role: 'Engenharia de Computação' },
      { id: '1359', name: 'David Matheus Conselvan', role: 'Engenharia de Computação' },
      { id: '1368', name: 'Fernando Alzueta', role: 'Engenharia de Computação' },
      { id: '1412', name: 'Luiza Ferreira Ehrenberger', role: 'Engenharia de Computação' },                   
    ],
    advisor: 'Marcel Parolin Jackowski',
    longDescription: 'Desenvolvimento de um cliente web moderno e seguro para monitoramento portuário, integrando sistemas de segurança inteligente e conversão de vídeo em tempo real para maior acessibilidade e conformidade.',
    tags: ['WebDevelopment','FullStack', 'VideoMonitoring','Cybersecurity'],
    partner: 'Intelbras'
  },
  {
    id: '202502015',
    title: 'Desenvolvimento de bancada de testes de resistência à água em produtos do setor agroindustrial',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://www.jassy.ag/wp-content/uploads/2019/08/Entrada_J.Assy_010819-1024x958.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1349', name: 'Breno Brolacci Schiavon', role: 'Engenharia Mecânica' },
      { id: '1225', name: 'Maia Fleider', role: 'Engenharia Mecatrônica' },
      { id: '1223', name: 'Leandra Ferreira Fontes', role: 'Engenharia Mecatrônica' },
      { id: '1416', name: 'Mariana Ribeiro Sávio', role: 'Engenharia Mecatrônica' },                   
    ],
    advisor: 'Fabio Ferraz Junior',
    longDescription: 'Desenvolvimento de uma bancada automatizada com CLP para testes de resistência à água e estanqueidade de componentes agroindustriais, seguindo normas internacionais de proteção.',
    tags: ['AgroTech','Estanqueidade','AutomacaoIndustrial','Sustainability'],
    partner: 'J.ASSY'
  },
  {
    id: '202502016',
    title: 'Protótipo de Validação Automatizada de Dados de Consumo de Energia com IA para Sustentabilidade',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://cdn.motor1.com/images/mgl/xWk8k/s1/mercedes-benz-social-distancing-logo.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1372', name: 'Giúlia Gomes Vallente', role: 'Ciência da Computação' },
      { id: '1357', name: 'Daniel da Rocha Prado', role: 'Ciência da Computação' },
      { id: '1348', name: 'Beni Sliozbergas', role: 'Ciência da Computação' },
      { id: '1341', name: 'Ana Helena Caiafa', role: 'Ciência da Computação' },                   
    ],
    advisor: 'Graziela Simone Tonin',
    longDescription: 'Implementação de um pipeline automatizado com IA e OCR para validar dados de consumo de energia e combustíveis, garantindo a integridade dos relatórios de emissões (ESG) da Mercedes-Benz.',
    tags: ['Sustainability','ESG'],
    partner: 'Mercedes-Benz'
  },
  {
    id: '202502017',
    title: 'Driving Behaviour de Condutores via Machine Learning',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://cms-gazzconecta.s3.amazonaws.com/gazzconecta/2020/07/31173437/Mottu-Stock-20-07-28-2067.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1374', name: 'Gustavo Barroso Souza Cruz', role: 'Ciência da Computação' },
      { id: '1442', name: 'Thiago Penha Pinheiro da Costa', role: ' Ciência da Computação' },
      { id: '1353', name: 'Caio Frigerio Liberal', role: 'Ciência da Computação' }                 
    ],
    advisor: 'Marcio Fernando Stabile Junior',
    longDescription: 'Desenvolvimento de modelos de Machine Learning para classificar perfis de condutores e prever riscos operacionais com base em padrões de uso e telemetria da frota.',
    tags: ['DrivingBehaviour','MachineLearning','DataScience'],
    partner: 'Mottu'
  },
  {
    id: '202502018',
    title: 'Inteligência Artificial na Manutenção Preditiva: Detecção de Anomalias Multivariáveis com Machine Learning',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://rockwellautomation.scene7.com/is/image/rockwellautomation/OurCompany-1.3840.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1218', name: 'Cleilton Sousa Serra', role: 'Engenharia Mecatrônica' },
      { id: '1446', name: 'Vinícius Garcia Lopes', role: 'Engenharia Mecatrônica' },
      { id: '1074', name: 'Natan Kron Goldenberg Lewi', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Carlos Magno de Oliveira Valente',
    longDescription: 'Desenvolvimento de uma solução de IA para detecção de anomalias multivariáveis e classificação automática de falhas industriais, integrada à plataforma FactoryTalk para manutenção preditiva em tempo real.',
    tags: ['MachineLearning','IIoT', 'PredictiveMaintenance'],
    partner: 'Rockwell Automation'
  },
  {
    id: '202502019',
    title: 'Exams PDF reader/converter',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://media.istockphoto.com/id/1267582949/pt/foto/tata-consultancy-services-ltd-offices.jpg?s=612x612&w=0&k=20&c=9hRIdip-umgtaetwdbPmJu9Sb3aeZ44GrmvOxNLTQTc=',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1214', name: 'Victor Pacheco dos Santos', role: 'Engenharia Mecânica' },
      { id: '1207', name: 'Guilherme da Franca Silva Escobar', role: 'Engenharia Mecânica' },
      { id: '1045', name: 'Guilherme Caproni de Faria', role: 'Engenharia de Computação' },                   
    ],
    advisor: 'Diego Pavan Soler',
    longDescription: 'Desenvolvimento de um sistema inteligente capaz de ler e extrair dados de exames médicos em PDF (digitais ou manuscritos) para integração automatizada em sistemas ERP.',
    tags: ['ComputerVision','HealthTech','DataScience'],
    partner: 'Tata Consultancy Services'
  },
  {
    id: '202502020',
    title: 'Control of medicine stock in hospitals and clinics',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://media.glassdoor.com/l/f1/50/78/19/tcs.jpg?signature=d634b502bfec8829e2f49a84546bad317f8039cbf7b7025ce37f33ee36d346f1',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1381', name: 'Henrique Manequini Rocha Pinto', role: 'Engenharia Mecatrônica' },
      { id: '1421', name: 'Nina Savoy de Sa', role: 'Ciência da Computação' },
      { id: '1385', name: 'Ian Cordibello Desponds', role: 'Ciência da Computação' },
      { id: '1221', name: 'Giselle Vieira de Melo', role: 'Engenharia Mecatrônica' },                   
      { id: '1378', name: 'Gustavo Rollo Dias Paulino', role: 'Engenharia Mecatrônica' },                   

    ],
    advisor: 'Alex Camilli Bottene',
    longDescription: 'Implementação de um sistema inteligente de controle de estoque para hospitais, focado na previsão de demanda e otimização da distribuição para eliminar desperdícios e garantir a disponibilidade de medicamentos.',
    tags: ['SupplyChain','InventoryOptimization','HospitalManagement',],
    partner: 'Tata Consultancy Services'
  },
  {
    id: '202502021',
    title: 'Chatbot Para Primeiro Atendimento',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://www.infomoney.com.br/wp-content/uploads/2025/10/weg-2.jpeg?fit=1280%2C853&quality=50&strip=all',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1366', name: 'Felipe Affonso Ribeiro de Maia', role: 'Engenharia de Computação' },
      { id: '1402', name: 'Luca Caruso', role: 'Engenharia de Computação' },
      { id: '1361', name: 'Eduardo Selber Castanho', role: 'Engenharia de Computação' },
      { id: '1380', name: 'Henrique Fazzio Badin', role: 'Engenharia de Computação' },                   
    ],
    advisor: 'Fabio Roberto de Miranda',
    longDescription: 'Desenvolvimento de um chatbot baseado em RAG para a WEG, capaz de realizar triagem técnica e responder dúvidas de colaboradores via Microsoft Teams, otimizando o fluxo de chamados internos.',
    tags: ['Chatbot','RAG','GenerativeAI','Industry40'],
    partner: 'WEG'
  },
  {
    id: '202502022',
    title: 'Sistema de Inteligência Artificial para Monitoramento Preditivo de Processos Industriais',
    description: '',
    semester: '2',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://veja.abril.com.br/wp-content/uploads/2026/03/WEG-Energia-Eolica-20171011-0877.jpeg.jpg?quality=70&strip=info',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1377', name: 'Gustavo Morin de Sousa', role: 'Engenharia Mecatrônica' },
      { id: '1389', name: 'João Antônio Gomes Garcia', role: 'Engenharia de Computação' },
      { id: '1397', name: 'Layne Pereira da Silva', role: 'Engenharia Mecatrônica' },
      { id: '1373', name: 'Guilherme Katayama Kaidei', role: 'Ciência da Computação' },
      { id: '1356', name: 'Carol Magario de Mattos Barretto', role: 'Engenharia Mecatrônica' },                   
    ],
    advisor: 'Lie Pablo Grala Pinto',
    longDescription: 'Desenvolvimento de um sistema de IA para monitoramento em tempo real de redes IIoT, focado na detecção de anomalias e previsão de falhas com alta precisão para evitar paradas produtivas.',
    tags: ['Industry40','IIoT','PredictiveMaintenance','MachineLearning',],
    partner: 'WEG'
  },
  {
    id: '2025010001',
    title: 'Sistema Computadorizado de Auxílio ao Diagnóstico de Câncer em Patologia Digital',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://accamargo.org.br/sites/default/files/styles/imagem_redonda_home/public/location/2024/07/itaim-fachada-red.jpg?h=8df58ce1&itok=-NnmUa1I',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1177', name: 'Diogo Pereira Lobo', role: 'Engenharia de Computação' },
      { id: '1199', name: 'Tales Ivalque Taveira de Freitas', role: 'Engenharia de Computação' },
      { id: '1175', name: 'Bruno Marques Li Volsi Falcao', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabio Jose Ayres',
    longDescription: 'Desenvolvimento de um sistema CAD que utiliza o modelo de fundação CHIEF para analisar lâminas digitais, fornecendo aos patologistas estimativas automatizadas da presença de câncer para auxiliar no diagnóstico.',
    tags: ['DigitalPathology','ComputerAidedDiagnosis','CAD','DeepLearning','HealthTech'],
    partner: 'A.C. Camargo'
  },
  {
    id: '2025010002',
    title: 'Desenvolvimento de um aparelho capaz de isolar e linearizar uma molécula única de DNA para estudo de biomarcadores no tratamento do câncer',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.BIOENGENHARIA,
    thumbnailUrl: 'https://d2yghbees9788u.cloudfront.net/saudebusiness/2025/07/shutterstock_2263273389-scaled.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1090', name: 'João Pedro Reis Lima', role: 'Engenharia Mecatrônica' },
      { id: '1073', name: 'Maria Eduarda Matta Mercer Mourao', role: 'Engenharia Mecânica' },
      { id: '1191', name: 'Nicolas Enzo Yassuda', role: 'Engenharia de Computação' },
      { id: '1077', name: 'Camila Bernardi Moniz', role: 'Engenharia Mecatrônica' },    
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Desenvolvimento de um equipamento de alta precisão para isolar e estirar moléculas individuais de DNA (DNA combing), permitindo a visualização de lacunas na fita simples e o estudo de mecanismos de resistência a quimioterápicos.',
    tags: ['LabEquipment','Biotec','DNACombing'],
    partner: 'A.C. Camargo'
  },
  {
    id: '2025010003',
    title: 'Desenvolvimento de algoritmos de análise de vídeo para interface com sistema de controle industrial',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://img.mirka.com/contenthubprod/globalassets/mirkacom/9d-company/news/abb-robot-with-aios-2200-1238.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1079', name: 'Diego Baptista Daurea Machado', role: 'Engenharia Mecatrônica' },
      { id: '1178', name: 'Douglas Pablo Bracale Celestino', role: 'Engenharia de Computação' },
      { id: '1183', name: 'Gustavo Mendes da Silva', role: 'Engenharia de Computação' },
      { id: '1100', name: 'Pedro Ivo de Rizzo', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Carlos Magno de Oliveira Valente',
    longDescription: 'Desenvolvimento de algoritmos de visão computacional aplicados à automação industrial para integração com sistemas de controle distribuído (DCS), visando demonstrações tecnológicas e inovação em processos produtivos.',
    tags: ['IndustrialAutomation','ComputerVision','DCS','Industry40','SmartManufacturing'],
    partner: 'ABB'
  },
  {
    id: '2025010004',
    title: 'Sistema de localização de carrinhos de supermercado',
    description: 'https://bhbfood.com/wp-content/uploads/2024/02/Walmart-.png',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: '',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1173', name: 'Arthur Moreira Tamm', role: 'Engenharia de Computação' },
      { id: '1098', name: 'Pedro Deslandes Castanheira Hun', role: 'Engenharia Mecatrônica' },
      { id: '1043', name: 'Felipe Menotti Trintim', role: 'Engenharia de Computação' },
      { id: '1172', name: 'Ariel Tamezgui Leventhal', role: 'Engenharia de Computação' },
    ],
    advisor: 'Silvio Szafir',
    longDescription: 'Implementação de um sistema de localização em tempo real (RTLS) utilizando tecnologia Ultra-Wideband (UWB) e processamento em borda para rastreio preciso de carrinhos inteligentes em ambientes indoor.',
    tags: ['IndoorPositioning','IoT','UWB','NVIDIAJetson','HardwareIntegration'],
    partner: 'Airis Tecnologia'
  },
  {
    id: '2025010005',
    title: 'Soluções IoT para Processamento de Sinais de Sensores de Vibração',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://ts2.tech/wp-content/uploads/2026/05/ambev-stock-faces-reality-check-after-brazil-beer-boom-and-ubs-sell-call-featured-4.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1205', name: 'Francisco Luiz Pereira da Silva', role: 'Engenharia Mecânica' },
      { id: '1103', name: 'Rodrigo Camargo Gomes', role: 'Engenharia Mecatrônica' },
      { id: '1219', name: 'Eduardo Heitor Penteado de Mello Peixoto', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Lie Pablo Grala Pinto',
    longDescription: 'Desenvolvimento de algoritmos para processamento local de sinais de vibração em dispositivos IoT, permitindo a detecção de falhas na borda (edge) para reduzir o consumo de energia e o tráfego de dados.',
    tags: ['IoT','Industry40','VibrationAnalysis','PredictiveMaintenance','EmbeddedSystems'],
    partner: 'Ambev'
  },
  {
    id: '2025010006',
    title: 'Energy Asset Grid Integration',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://cdn.shopify.com/s/files/1/0555/4601/9918/files/Boldr_App_Website_Magazine_Covers_4_2048x2048.jpg?v=1726053669',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1032', name: 'Arthur Boschini da Fonseca', role: 'Engenharia de Computação' },
      { id: '1050', name: 'Joseph Kallas Neto', role: 'Engenharia de Computação' },
      { id: '1211', name: 'Pedro Ribeiro Lodi', role: 'Engenharia Mecânica' },
      { id: '1039', name: 'Dom Ruan Suzano Figueira da Silva', role: 'Engenharia de Computação' },
    ],
    advisor: 'Raul Ikeda Gomes da Silva',
    longDescription: 'Integração de sistemas via API para criar uma Usina Virtual (VPP), permitindo o controle automatizado de dispositivos de climatização para reduzir a carga na rede elétrica durante picos de demanda e diminuir a dependência de combustíveis fósseis.',
    tags: ['VirtualPowerPlant','EnergyManagement','SmartGrid','IoT','EnergyEfficiency'],
    partner: 'Boldr'
  },
  {
    id: '2025010007',
    title: 'Desenvolvimento de um kit de acoplamento para unir um patinete elétrico a uma cadeira de rodas',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://i0.statig.com.br/bancodeimagens/cn/72/vp/cn72vpkkg5u62v6izzjsr3aij.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1208', name: 'Matheus de Freitas Souza', role: 'Engenharia Mecânica' },
      { id: '1201', name: 'Bruno Conte Paiva', role: 'Engenharia Mecânica' },
      { id: '1209', name: 'Matheus Lopes Vilar', role: 'Engenharia Mecânica' },
      { id: '1207', name: 'Guilherme da Franca Silva Escobar', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Victor Antonio Seixas de Menezes Paiva',
    longDescription: 'Desenvolvimento do KOM-BEE, um triciclo elétrico modular projetado para transporte de passageiros, logística de última milha e coleta seletiva, incluindo soluções de acoplamento para acessibilidade.',
    tags: ['ElectricVehicle','Micromobility','Accessibility','MechanicalEngineering','ProductDesign'],
    partner: 'Cicloway'
  },
  {
    id: '2025010008',
    title: 'RISC-V para Uso Aeroespacial',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://portal-adm.campinas.sp.gov.br/sites/default/files/noticias/img-avulsa/cti%20renato%20archer.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1192', name: 'Pedro Balbo Portella', role: 'Engenharia de Computação' },
      { id: '1035', name: 'Caio Bertolani Travain', role: 'Engenharia de Computação' },
      { id: '1193', name: 'Pedro Cliquet do Amaral', role: 'Engenharia de Computação' },
      { id: '1058', name: 'Pedro Paulo Moreno Camargo', role: 'Engenharia de Computação' },
      { id: '1108', name: 'Jadon Dewey', role: 'Engenharia Elétrica, Texas A&M University' },
      { id: '1107', name: 'Eddie Villegas', role: 'Engenharia Elétrica, Texas A&M University' },

    ],
    advisor: 'Rafael Corsi Ferrão',
    longDescription: 'Exploração e aprimoramento da arquitetura RISC-V para aplicações aeroespaciais, visando o desenvolvimento de sistemas tolerantes a falhas e a criação de um chip (ASIC) nacional para uso governamental.',
    tags: ['RISCV','Aerospace','EmbeddedSystems','ComputerArchitecture','FaultTolerance'],
    partner: 'CTI Renato Archer'
  },
  {
    id: '2025010009',
    title: 'Guardrails em IA Generativa',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://classic.exame.com/wp-content/uploads/2025/05/Foto-1_abre.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1198', name: 'Rodrigo Paoliello de Medeiros', role: 'Engenharia de Computação' },
      { id: '1181', name: 'Gabriel Mendonça de Mello Hermida', role: 'Engenharia de Computação' },
      { id: '1180', name: 'Fernanda de Oliveira Pereira', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabricio Jailson Barth',
    longDescription: 'Implementação de uma arquitetura modular de segurança (guardrails) para IA Generativa, capaz de filtrar toxicidade, evitar alucinações e proteger contra vazamento de dados e ataques de jailbreak em assistentes virtuais.',
    tags: ['GenerativeAI','Guardrails','LLM','PromptEngineering','ArtificialIntelligence'],
    partner: 'Dell Technologies'
  },
  {
    id: '2025010010',
    title: 'Implementação de Navegação Autônoma em Veículo Terrestre: Aprimoramento e Testes',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://www.embrapa.br/image/journal/article?img_id=116427106&t=1779230520212',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1222', name: 'Guilherme Garrido Klingelfus Pinheiro', role: 'Engenharia Mecatrônica' },
      { id: '1212', name: 'Rafael Pacheco Paolino', role: 'Engenharia Mecânica' },
      { id: '1190', name: 'Matheus Ribeiro Barros', role: 'Engenharia de Computação' },
      { id: '1174', name: 'Bruna Lima Meinberg', role: 'Engenharia de Computação' },
    ],
    advisor: 'Vinicius Licks',
    longDescription: 'Aprimoramento físico e lógico de um robô autônomo para monitoramento agrícola, focando na otimização da locomoção e na precisão dos algoritmos de navegação em terrenos irregulares.',
    tags: ['AutonomousNavigation','AgroTech','Robotics','MechanicalOptimization','PrecisionAgriculture'],
    partner: 'Embrapa'
  },
  {
    id: '2025010011',
    title: 'Seleção Inteligente de Minigames para o Jogo Arena of Dreams',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://play-lh.googleusercontent.com/A4wtoDzw2Gt0ZB1VEyR9acHpd3jRxzljCbfLPuoFQMsmwQl9MrAlCIZxx-40gY4zag',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '591', name: 'Luca Cazzolato Machado', role: 'Engenharia de Computação' },
      { id: '1196', name: 'Pedro Henrique Rizo Colpas', role: 'Engenharia de Computação' },
      { id: '1194', name: 'Pedro Fracassi', role: 'Engenharia de Computação' },
    ],
    advisor: 'Tiago Sanches da Silva',
    longDescription: 'Substituição de sistemas aleatórios por um algoritmo de seleção inteligente em jogos mobile, utilizando embeddings multidimensionais para reduzir a percepção de repetitividade e aumentar o engajamento dos jogadores.',
    tags: ['GameDesign','ComputerVision','Embeddings','UserExperience','MobileGaming'],
    partner: 'Fanatee'
  },
  {
    id: '2025010012',
    title: 'Impressão de Peças em Resina',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://fiberbus.com.br/images/services/pintura/pintura_g.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1214', name: 'Victor Pacheco dos Santos', role: 'Engenharia Mecânica' },
      { id: '1095', name: 'Luca Oshiro Camargo', role: 'Engenharia Mecatrônica' },
      { id: '1213', name: 'Rodrigo Bandeira Villela', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Gustavo Pollettini Marcos',
    longDescription: '',
    tags: ['3DPrinting','AdditiveManufacturing','ResinPrinting','IndustrialDesign','MechanicalTesting'],
    partner: 'Estudo comparativo de tecnologias de impressão 3D (DLP e PolyJet) e usinagem CNC utilizando resinas de alto desempenho para a produção de coberturas de mecanismos de portas, com foco em acabamento estético e resistência mecânica.'
  },
  {
    id: '2025010013',
    title: '123Ask',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://static.poder360.com.br/2024/06/fintalk-848x477.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1169', name: 'Alberto Mansur', role: 'Engenharia de Computação' },
      { id: '1186', name: 'Kevin Nagayuki Shinohara', role: 'Engenharia de Computação' },
      { id: '1045', name: 'Guilherme Caproni de Faria', role: 'Engenharia de Computação' },
      { id: '1038', name: 'Caroline Chaim de Lima Carneiro', role: 'Engenharia de Computação' },
    ],
    advisor: 'Tiago Fernandes Tavares',
    longDescription: 'Desenvolvimento de um sistema de tradução de linguagem natural para SQL (Text-to-SQL) utilizando LLMs, permitindo que usuários realizem consultas complexas em bancos de dados dinâmicos através de perguntas simples.',
    tags: ['TextToSQL','NaturalLanguageProcessing','GenerativeAI','BusinessIntelligence','SoftwareArchitecture'],
    partner: 'Fintalk'
  },
  {
    id: '2025010014',
    title: 'Aplicação web para monitoramento de feedbacks de usuários, integrada a um aplicativo voltado à democratização de línguas indígenas',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://sitepd.org.br/wp-content/uploads/2024/10/IBM-integra-lista-de-33-multinacionais-investigadas-por-formacao-de-cartel-no-Brasil-1.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1184', name: 'Isabella dos Santos de Amorim', role: 'Engenharia de Computação' },
      { id: '1171', name: 'Ana Laiz Novais de Farias', role: 'Engenharia de Computação' },
      { id: '1044', name: 'Giovana Cassoni Andrade', role: 'Engenharia de Computação' },
      { id: '1229', name: 'Samuel Koch', role: 'Engenharia Elétrica, Texas A&M University' },
      { id: '1230', name: 'Nicholas Petersilge', role: 'Engenharia Elétrica, Texas A&M University' },
    ],
    advisor: 'Graziela Simone Tonin',
    longDescription: 'Desenvolvimento de uma plataforma web de monitoramento e integração de coleta de feedbacks em um aplicativo de tradução, visando o aprimoramento de modelos de IA para a preservação da língua indígena Nheengatu.',
    tags: ['IndigenousLanguages','WebDevelopment','UserFeedback','SocialImpact','LanguageModel'],
    partner: 'IBM Brasil'
  },
  {
    id: '2025010015',
    title: 'Automação de Bancada de Testes para Sensores de Fluxo Implementados em Cultivadoras',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AUTOMACAO_INDUSTRIAL,
    thumbnailUrl: 'https://www.jassy.ag/wp-content/uploads/2019/08/Entrada_J.Assy_010819-1024x958.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1226', name: 'Ralph Michaan', role: 'Engenharia Mecatrônica' },
      { id: '1216', name: 'Augusto Monteiro Giuliani', role: 'Engenharia Mecatrônica' },
      { id: '1228', name: 'Taina Pereira de Bonfim', role: 'Engenharia Mecatrônica' },
      { id: '1217', name: 'Bruno Olivares Sanchez', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Fabio Ferraz Junior',
    longDescription: 'Automação de uma bancada de testes hidráulica para sensores de fluxo agrícola, utilizando CLP e interface LabVIEW para garantir a precisão, rastreabilidade e eficiência na detecção de obstruções em sistemas de plantio.',
    tags: ['IndustrialAutomation','PLC','LadderLogic','AgroTech','TestBench'],
    partner: 'J.ASSY'
  },
  {
    id: '2025010016',
    title: 'Automatização do controle de movimentação de localização de obras do acervo do MASP',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO, 
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/MASP_Brazil.jpg/1280px-MASP_Brazil.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1195', name: 'Pedro Gomes de Sá Drumond', role: 'Engenharia de Computação' },
      { id: '1170', name: 'Alexandre Rodrigues Santarossa', role: 'Engenharia de Computação' },
      { id: '1074', name: 'Natan Kron Goldenberg Lewi', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Luiz Fernando Cardoso dos Santos Durão',
    longDescription: 'Desenvolvimento de um sistema de automação e rastreamento de obras de arte via QR Code integrado ao sistema de gestão do MASP, visando eliminar erros manuais e otimizar a segurança na movimentação do acervo.',
    tags: ['InformationSystems','InventoryManagement','AssetTracking','MuseumTech','Logistics'],
    partner: 'MASP'
  },
  {
    id: '2025010017',
    title: 'Utilização de compósitos no mercado automotivo pesado e agrícola',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.ADMINISTRACAO,
    thumbnailUrl: 'https://l3.com.br/wp-content/uploads/2022/11/Foto_Iochpe.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1210', name: 'Pedro Henrique Cardoso Peretto', role: 'Engenharia Mecânica' },
      { id: '1206', name: 'Guido Lacerda Soares do Couto Rosa', role: 'Engenharia Mecânica' },
      { id: '1220', name: 'Enzo Martins Barroso del Manto', role: 'Engenharia Mecatrônica' },
      { id: '1202', name: 'Eduardo Antoniazzi Zetone', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Israel Ferreira Alves',
    longDescription: 'Estudo de viabilidade técnica e comercial para a aplicação de materiais compósitos em veículos pesados e agrícolas, incluindo dimensionamento de mercado e o desenvolvimento de uma ferramenta para seleção de processos de fabricação.',
    tags: ['MarketAnalysis','AutomotiveIndustry','AgroTech','MaterialSubstitution','ManufacturingProcesses'],
    partner: 'Maxion Structural Components'
  },
  {
    id: '2025010018',
    title: 'Otimizando o Abastecimento de Estoque por meio de Inteligência Computacional',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://s2-pipelinevalor.glbimg.com/L6Lj6cRNCIqZhMWN-Dsac7hp8B8=/0x0:8001x4501/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_b3309463db95468aa275bd532137e960/internal_photos/bs/2022/n/k/FWeiB8QhyO5Kjt9mHzvA/mevo-links-1-40.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1036', name: 'Caio de Camargo Aranha Tieri', role: 'Engenharia de Computação' },
      { id: '856', name: 'Pedro Osborn Mahfuz', role: 'Engenharia de Computação' },
      { id: '1187', name: 'Luana Wilner Abramoff', role: 'Engenharia de Computação' },
      { id: '1063', name: 'Thomas Cavalcanti Chabro', role: 'Engenharia de Computação' },
    ],
    advisor: 'Rodolfo da Silva Avelino',
    longDescription: 'Desenvolvimento de um sistema de inteligência computacional e API de suporte à decisão para otimizar o abastecimento de estoque da Mevo, gerando recomendações de compra baseadas em dados históricos e restrições de inventário.',
    tags: ['DataScience','DataDriven','StockOptimization','HealthTech','InventoryManagement'],
    partner: ''
  },
  {
    id: '2025010019',
    title: 'Negociação entre agentes de IA Generativa para comunicação em Spatial Web',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://itforum.com.br/wp-content/uploads/2023/09/NTT-Data-adquire-Conexos.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1189', name: 'Matheus Raffaelle Nery Castellucci', role: 'Engenharia de Computação' },
      { id: '1182', name: 'Gustavo Eliziario Stevenson de Oliveira', role: 'Engenharia de Computação' },
      { id: '1176', name: 'Caio Ortega Bôa', role: 'Engenharia de Computação' },
      { id: '1185', name: 'João Pedro Rodrigues dos Santos', role: 'Engenharia de Computação' },
    ],
    advisor: 'Luciano Pereira Soares',
    longDescription: 'Desenvolvimento de um sistema de agentes autônomos de IA Generativa dotados de memória computacional, capazes de navegar, interagir e negociar de forma independente entre si dentro de um ambiente virtual 3D.',
    tags: ['GenerativeAI','LLM','MultiAgentSystems','VirtualEnvironments','AutonomousAgents'],
    partner: 'NTT Data Brasil'
  },
  {
    id: '2025010020',
    title: 'Estudo de plantabilidade e sujidade na produção de sementes de milho',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.ADMINISTRACAO,
    thumbnailUrl: 'https://www.syngenta.com.br/sites/g/files/kgtney466/files/styles/v2_image_default/public/media/image/2025/12/04/syngenta_logo.jpg?itok=YnnimrBh',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1204', name: 'Filippo Ferraro', role: 'Engenharia Mecânica' },
      { id: '1200', name: 'Alfredo Montingelli Villela', role: 'Engenharia Mecânica' },
      { id: '1203', name: 'Fernando Campos Kaizer', role: 'Engenharia Mecânica' },
      { id: '1224', name: 'Luiz Gustavo Strenger Domingues de Castro Reis', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Aplicação da metodologia DMAIC no processo de beneficiamento de sementes da Syngenta para otimizar os protocolos de amostragem e inspeção, mitigando falhas de sujidade e plantabilidade antes da distribuição ao cliente final.',
    tags: ['QualityControl','ProcessEngineering','AgroTech','ContinuousImprovement','Agribusiness'],
    partner: 'Syngenta Seeds'
  },
  {
    id: '2025010021',
    title: 'Plataforma para Gerenciamento de Dados de Abastecimentos em Grandes Frotas',
    description: '',
    semester: '1',
    year: 2025,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://www.infomoney.com.br/wp-content/uploads/2024/07/versa-fuel-van.jpeg?quality=70',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1188', name: 'Luca Mizrahi', role: 'Engenharia de Computação' },
      { id: '1197', name: 'Pedro Toledo Piza Civita', role: 'Engenharia de Computação' },
      { id: '1086', name: 'Gabriel Barreto da Costa Barbosa', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Maciel Calebe Vidal',
    longDescription: 'Desenvolvimento de um dashboard gerencial em Power BI integrado ao BigQuery para automatizar a análise de dados de abastecimento de grandes frotas, eliminando planilhas manuais e fornecendo insights estratégicos para a Versa Fuel.',
    tags: ['BusinessIntelligence','DataVisualization','PowerBI','BigQuery','Dashboards'],
    partner: 'Versa Fuel'
  },
  {
    id: '2024020001',
    title: 'Desenvolvimento de Software de Simulação de Engenharia Aeronáutica',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.SIMULACAO,
    thumbnailUrl: 'https://mundogeo.com/wp-content/uploads/2024/02/22073911/akaer-akr-h2-divulgacao-800x400.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1065', name: 'Vinicius Matheus Morales', role: 'Engenharia de Computação' },
      { id: '1095', name: 'Luca Oshiro Camargo', role: 'Engenharia Mecatrônica' },
      { id: '1028', name: 'André Felipe Bulcão Brito', role: 'Engenharia de Computação' },
      { id: '1074', name: 'Natan Kron Goldenberg Lewi', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Paulo Roberto Bufacchi Mendes',
    longDescription: 'Desenvolvimento de um software em Python para simulação de voo com seis graus de liberdade e modelagem atmosférica ISA, voltado para a validação e otimização de componentes aeroespaciais da Akaer em conformidade com padrões da NASA.',
    tags: ['FlightSimulation','Aerospace','Aerodynamics','ComputationalSimulation','SoftwareEngineering'],
    partner: 'Akaer em colaboração com a Confederação Nacional da Indústria'
  },
  {
    id: '2024020002',
    title: 'Uso de IA para sistema de orientação e guiagem para pouso semiautônomos de um VANT',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://www.defesanet.com.br/wp-content/uploads/2023/04/UAV-Hibrido-FINEP3679.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1096', name: 'Mateus Ruggero de Oliveira', role: 'Engenharia Mecatrônica' },
      { id: '1080', name: 'Enzo Dadier Lacks Zamberlan', role: 'Engenharia Mecatrônica' },
      { id: '1106', name: 'Vinicius Gallo', role: 'Engenharia Mecatrônica' },
      { id: '1075', name: 'Alessandra Yumi Carvalho Ogawa', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Akaer em colaboração com a Confederação Nacional da Indústria',
    longDescription: 'Desenvolvimento de um sistema de guiagem e orientação baseado em visão computacional (YOLOv3) treinado na Unreal Engine 5, permitindo o pouso semiautônomo, desvio de obstáculos e rotinas de segurança para um VANT cargueiro.',
    tags: ['ComputerVision','DroneLanding','AutonomousSystems','ArtificialIntelligence','Aerospace'],
    partner: 'Akaer em colaboração com a Confederação Nacional da Indústria'
  },
  {
    id: '2024020003',
    title: 'Análise de Dados para Apoiar a Tomada de Decisão na Gestão de Ativos de Energia',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://www.seudinheiro.com/uploads/2024/08/Design-sem-nome.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1083', name: 'Felipe Blasbalg', role: 'Engenharia Mecatrônica' },
      { id: '1048', name: 'Jerônimo de Abreu Afrange', role: 'Engenharia de Computação' },
      { id: '1082', name: 'Enzo Stefani Vita Cunha', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Lie Pablo Grala Pinto',
    longDescription: 'Desenvolvimento de uma ferramenta de análise de dados e Machine Learning para a manutenção preditiva de bombas hidráulicas na Usina Hidrelétrica de São José (Alupar), transformando dados de operação em previsões de falhas.',
    tags: ['DataScience','MachineLearning','PredictiveMaintenance','EnergySector','AssetManagement'],
    partner: 'Alupar'
  },
  {
    id: '2024020004',
    title: 'Desenvolvimento de IoT para Monitoramento das Geladeiras AMBEV',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://forbes.com.br/wp-content/uploads/2017/03/58-Ambev-rep.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1071', name: 'João Pedro Ramos Fiorin', role: 'Engenharia Mecânica' },
      { id: '1099', name: 'Pedro Henrique de Sousa da Silva', role: 'Engenharia Mecatrônica' },
      { id: '1089', name: 'Grasielly Almeida Lima', role: 'Engenharia Mecatrônica' },
      { id: '1078', name: 'Camila Soares Magni', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Silvio Szafir',
    longDescription: 'Desenvolvimento de um dispositivo IoT e revisão de hardware industrial para monitoramento em tempo real de temperatura, movimentação e geolocalização das geladeiras da Ambev, integrando sensores e transmissão via MQTT para otimização logística.',
    tags: ['IoT','EmbeddedSystems','AssetTracking','HardwareDesign'],
    partner: 'Ambev'
  },
  {
    id: '2024020005',
    title: 'Desenvolvimento de um Sistema de Manutenção Preditiva Aplicado a Compressores Industriais',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://estadaori.estadao.com.br/wp-content/uploads/2024/05/AdobeStock_408681226_Editorial_Use_Only.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1097', name: 'Paola Brancaccio Bohana Simões Friedel', role: 'Engenharia Mecatrônica' },
      { id: '1102', name: 'Raphael Jacob Butori', role: 'Engenharia Mecatrônica' },
      { id: '1053', name: 'Lucas Gurgel Novais', role: 'Engenharia de Computação' },
      { id: '1085', name: 'Gabriela Albuquerque Alves', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Fabio Ferraz Junior',
    longDescription: 'Desenvolvimento de um framework de ciência de dados focado em manutenção preditiva para compressores industriais, utilizando algoritmos de aprendizado de máquina não supervisionado e análise de frequência para detecção precoce de anomalias.',
    tags: ['DataScience','MachineLearning','PredictiveMaintenance','SignalProcessing','IndustrialAutomation'],
    partner: 'Ambev'
  },
  {
    id: '2024020006',
    title: 'ChatBot De Educação Financeira',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://classic.exame.com/wp-content/uploads/2021/11/WhatsApp-Image-2021-10-29-at-16.17.07.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1011', name: 'Fernando Vieira dos Santos', role: 'Ciência da Computação' },
      { id: '1025', name: 'Sergio Eduardo Ramella Junior', role: 'Engenharia de Computação' },
      { id: '1076', name: 'Arthur Motta Pereira Gomes', role: 'Engenharia Mecatrônica' },
      { id: '1088', name: 'Gabriel Zahar Mine', role: 'Engenharia Mecatrônica' },
      { id: '1051', name: 'Leonardo da França Moura de Andrade', role: 'Engenharia de Computação' },
    ],
    advisor: 'Graziela Simone Tonin',
    longDescription: 'Otimização e aprimoramento do assistente virtual de inteligência artificial generativa da B3, focado em fornecer respostas didáticas e seguras sobre o mercado financeiro para investidores iniciantes.',
    tags: ['ArtificialIntelligence','GenerativeAI','ChatBot','LLM','PromptEngineering'],
    partner: ''
  },
  {
    id: '2024020007',
    title: 'Estimating Room Temperature Arrival Time',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://hackster.imgix.net/uploads/attachments/1606267/image_f490GvizWd.png?auto=compress%2Cformat&w=830&h=466.875&fit=min&dpr=2.625',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1084', name: 'Felipe Martins da Costa Drummond', role: 'Engenharia Mecatrônica' },
      { id: '894', name: 'Adney Costa Moura', role: 'Engenharia de Computação' },
      { id: '895', name: 'Lorran Caetano Machado Lopes', role: 'Engenharia de Computação' },
      { id: '1027', name: 'Tomas Rodrigues Alessi', role: 'Ciência da Computação' },
    ],
    advisor: 'Rodrigo Carareto',
    longDescription: 'Desenvolvimento de um modelo preditivo de ciência de dados integrado ao dispositivo IoT Klima (Boldr) para estimar a curva de decaimento de temperatura de cômodos, com exibição dos resultados no aplicativo móvel e via atualização de firmware no display físico do aparelho.',
    tags: ['DataScience','PredictiveModeling','IoT','EmbeddedSystems','CloudComputing'],
    partner: 'Boldr'
  },
  {
    id: '2024020008',
    title: 'AVALIAÇÃO DE FERRAMENTA DE DESIGN ORIENTADO A CIRCULARIDADE',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.ADMINISTRACAO,
    thumbnailUrl: 'https://i.metroimg.com/dWYBRvU5eWfExOiED4HTD0cXArK4_z4l3WB-cVxFybw/w:900/q:85/f:webp/plain/https://images.metroimg.com/2025/08/07084146/braskem-11.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1070', name: 'João Pedro Artese de Natal', role: 'Engenharia Mecânica' },
      { id: '1069', name: 'João Manoel Pasqua Filho', role: 'Engenharia Mecânica' },
      { id: '1067', name: 'Henrique Gabriel Oliveira Silva', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Alex Camilli Bottene',
    longDescription: 'Avaliação de uma ferramenta de tomada de decisão desenvolvida para a Braskem, que utiliza análises de sensibilidade e workshops industriais para quantificar o Índice de Circularidade de Materiais (MCI) e avaliar a relação Custo X Circularidade em embalagens plásticas.',
    tags: ['CircularEconomy','CostBenefit','Sustainability','SensitivityAnalysis','PackagingDesign'],
    partner: 'Braskem'
  },
  {
    id: '2024020009',
    title: 'Exploring RISC-V CPU for Aerospace Applications',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.EMBARCADOS,
    thumbnailUrl: 'https://www.acidadeon.com/campinas/wp-content/uploads/sites/5/2025/04/cti-renato-archer_2025-04-04_21-39-39_jpg_2025-04-04_21-39-39.webp',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1005', name: 'Eduardo Schneider Monteiro de Barros', role: 'Ciência da Computação' },
      { id: '1062', name: 'Rodrigo Anciães Patelli', role: 'Engenharia de Computação' },
      { id: '1064', name: 'Victor Luis Gama de Assis', role: 'Engenharia de Computação' },
      { id: '1034', name: 'Arthur Martins de Souza Barreto', role: 'Engenharia de Computação' },
      { id: '1108', name: 'Jadon Dewey', role: 'Engenharia Elétrica, Texas A&M University' },
      { id: '1107', name: 'Eddie Villegas', role: 'Engenharia Elétrica, Texas A&M University' },
    ],
    advisor: 'Rafael Corsi Ferrão',
    longDescription: 'Análise e implementação de algoritmos de controle de motores (Six-Step e FOC) em CPUs de arquitetura aberta RISC-V, avaliando requisitos de tempo real e hardware para aplicações no setor aeroespacial brasileiro.',
    tags: ['EmbeddedSystems','Aerospace','Microprocessors','RealTimeSystems','Semiconductors'],
    partner: 'CTI Renato Archer'
  },
  {
    id: '2024020010',
    title: 'Modelagem financeira de alta frequência com Big Data e Machine Learning',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://files.sunoresearch.com.br/p/uploads/2019/04/modelagem-financeira.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1056', name: 'Marlon Silva Pereira', role: 'Engenharia de Computação' },
      { id: '1046', name: 'Guilherme dos Santos Martins', role: 'Engenharia de Computação' },
      { id: '1010', name: 'Felipe Maluli de Carvalho Dias', role: 'Ciência da Computação' },
    ],
    advisor: 'Maciel Calebe Vidal',
    longDescription: 'Desenvolvimento de uma infraestrutura escalável de Big Data integrada ao banco de dados QuestDB para processamento de cotações intradiárias, servindo de base para a criação de modelos preditivos de Machine Learning aplicados ao Factor Investing.',
    tags: ['DataScience','MachineLearning','BigData','FinancialModeling','HighFrequencyTrading'],
    partner: 'DAO Capital'
  },
  {
    id: '2024020011',
    title: 'Doc Explorer Linguistic & Layout: Explorando Ferramentas de Inteligência Artificial para Extração de Informações de Documentos Semi Estruturados',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://www.hardlink.com.br/novo/wp-content/uploads/2026/05/1x1_Dell-Technologies-World-2026.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1020', name: 'Marcelo Rabello Barranco', role: 'Ciência da Computação' },
      { id: '1008', name: 'Erik Leonardo Soares de Oliveira', role: 'Ciência da Computação' },
      { id: '1055', name: 'Marcos Vinícius da Silva', role: 'Engenharia de Computação' },
      { id: '1026', name: 'Thomas Chiari Ciocchetti de Souza', role: 'Ciência da Computação' },
    ],
    advisor: 'Michel Silva Fornaciali',
    longDescription: 'Exploração e implementação de tecnologias de Inteligência Artificial Generativa e visão computacional para automatizar a extração e a consulta de informações em documentos PDF semiestruturados de alta diversidade na Dell.',
    tags: ['ArtificialIntelligence','GenerativeAI','DocumentAI','DataScience','InformationExtraction'],
    partner: ''
  },
  {
    id: '2024020011',
    title: 'Veículo Terrestre Autônomo para Monitoramento de Talhões de Silvicultura e Plantações de Frutas',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.ROBOTICA,
    thumbnailUrl: 'https://www.insper.edu.br/content/dam/insper-portal/imagens/alunos/capstone.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1060', name: 'Rafael Eli Katri', role: 'Engenharia de Computação' },
      { id: '1094', name: 'Luana de Matos Sorpreso', role: 'Engenharia Mecatrônica' },
      { id: '1042', name: 'Felipe Catapano Emrich Melo', role: 'Engenharia de Computação' },
      { id: '1087', name: 'Gabriel Brunoro Motta Tumang', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Vinicius Licks',
    longDescription: 'Desenvolvimento de um sistema de navegação autônoma para um robô agrícola utilizando ROS 2 e a stack Nav2, aplicando algoritmos de SLAM e fusão multissensorial para mapeamento e deslocamento em terrenos irregulares de silvicultura e pomares.',
    tags: ['Robotics','SmartFarming','AutonomousVehicles','AgroTech','Automation'],
    partner: 'Embrapa'
  },
  {
    id: '2024020012',
    title: 'PEIXE-ROBÔ – Veículo Submergível Semiautônomo (Fase 2)',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://www.embrapa.br/bme_images/o/170920040o.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '1105', name: 'Thiago Teixeira dos Santos', role: 'Engenharia Mecatrônica' },
      { id: '1052', name: 'Lincoln Rodrigo Pereira Melo', role: 'Engenharia de Computação' },
      { id: '873', name: 'Lourenco Azevedo de Paula', role: 'Engenharia Mecânica' },
      { id: '1101', name: 'Quézia Pereira da Silva Moura', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Carlos Eduardo de Brito Novaes',
    longDescription: 'Segunda fase do desenvolvimento de um peixe-robô submergível para a Embrapa, integrando controle moderno de submersão (LQR e Filtro de Kalman), vedação física aprimorada e telemetria sem fio via tecnologia LoRa para monitoramento de tanques de tilápia.',
    tags: ['Robotics','EmbeddedSystems','Biomimetics','UnderwaterRobotics','AgroTech'],
    partner: 'Embrapa'
  },
  {
    id: '2024020013',
    title: 'Integração de Linguagem Natural para Aprimoramento da Experiência do Paciente em Hospitais',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://img.odcdn.com.br/wp-content/uploads/2023/06/IA-medicina.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '1021', name: 'Marcelo Vampré Ferreira Marchetto', role: 'Ciência da Computação' },
      { id: '1017', name: 'Leonardo Scarlato', role: 'Ciência da Computação' },
      { id: '1049', name: 'João Gabriel Valentim Rocha', role: 'Engenharia de Computação' },
      { id: '1047', name: 'Hudson Monteiro Araújo', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabio Jose Ayres',
    longDescription: 'Desenvolvimento de uma ferramenta analítica baseada em processamento de linguagem natural e redução de dimensionalidade para automatizar a classificação e visualização de reviews de pacientes, agilizando a gestão de Customer Experience do Hospital Sírio-Libanês.',
    tags: ['DataScience','CustomerExperience','HealthcareTech','TextAnalytics','DataVisualization'],
    partner: 'Hospital Sírio-Libanês'
  },
  {
    id: '2024020014',
    title: 'Desenvolvimento de dispositivo multicanal acoplável para endoscópios comerciais',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.HARDWARE,
    thumbnailUrl: 'https://hospitalsiriolibanes.org.br/sites/institucional/files/2025-12/interna_belavista-1.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '896', name: 'Leticia Teles Machado', role: 'Engenharia Mecânica' },
      { id: '1068', name: 'Henrique Moura Costa Damico', role: 'Engenharia Mecânica' },
      { id: '1072', name: 'Jose Edson Mendonça Ribeiro Lima Araujo', role: 'Engenharia Mecânica' },
    ],
    advisor: 'Raphael Galdino dos Santos',
    longDescription: 'Desenvolvimento e validação ex-vivo de um dispositivo mecânico multicanal acoplável a endoscópios comerciais, projetado via metodologia PDP e CPM, permitindo a operação simultânea de múltiplas ferramentas para redução do tempo cirúrgico.',
    tags: ['HardwareDesign','MedicalDevices','BiomedicalEngineering','ProductDevelopment','SurgicalInnovation'],
    partner: 'Hospital Sírio-Libanês'
  },
  {
    id: '2024020015',
    title: 'Conceitualização De Uma Linha De Desmontagem De Cartuchos De Tinta De Impressora Para Circularidade',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.MANUFATURA_AVANCADA,
    thumbnailUrl: 'https://media.alquimio.cloud/images/@thumbs_500_1163749983654defae6509aed0a00c5af9f01617.webp',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1104', name: 'Rodrigo de Lima Azeredo', role: 'Engenharia Mecatrônica' },
      { id: '1093', name: 'Lorena Barbosa Antunes da Silva', role: 'Engenharia Mecatrônica' },
      { id: '1092', name: 'Livia Brigido do Nascimento', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Carlos Magno de Oliveira Valente',
    longDescription: 'Conceitualização e modelagem de uma linha de desmontagem automatizada para cartuchos de tinta usados da HP, utilizando a metodologia PDP e testes preliminares de separação para viabilizar a reciclagem e reinserção de polímeros na cadeia produtiva.',
    tags: ['AdvancedManufacturing','IndustrialAutomation','Sustainability','ProductDevelopment','ReverseLogistics'],
    partner: 'HP'
  },
  {
    id: '2024020016',
    title: 'Desenvolvimento de aplicativo Android para facilitar a escrita em Nheengatu',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://portalamazonia.com/wp-content/uploads/2025/06/constituicao-recebeu-versao-nheengatu-Foto-Fellipe-Sampaio-STF.jpeg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.DESTAQUE,
    students: [
      { id: '866', name: 'Vitor Irulegui Bueno Bandeira', role: 'Engenharia de Computação' },
      { id: '1013', name: 'Gustavo Lindenberg Pacheco', role: 'Ciência da Computação' },
      { id: '1012', name: 'Gustavo Antony de Assis', role: 'Ciência da Computação' },
      { id: '1033', name: 'Arthur Cisotto Machado', role: 'Engenharia de Computação' },
      { id: '1230', name: 'Nicholas Petersilge', role: 'Engenharia Elétrica, Texas A&M University' },
      { id: '1229', name: 'Samuel Koch', role: 'Engenharia Elétrica, Texas A&M University' },
    ],
    advisor: 'Tiago Fernandes Tavares',
    longDescription: 'Desenvolvimento de um aplicativo móvel Android para a preservação e escrita da língua indígena Nheengatu, integrando serviços de IA e tradução da IBM a uma interface otimizada para usabilidade e integrada a apps de mensagens.',
    tags: ['AndroidDevelopment','SoftwareEngineering','IndigenousLanguages','SocialInnovation','MobileApp'],
    partner: 'IBM Brasil'
  },
  {
    id: '2024020017',
    title: 'Uso de Câmeras de Segurança para detecção de armas de fogo',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://backend.intelbras.com/sites/default/files/2022-10/camera-bullet-com-entrada-de-alarme-vip-3280-b-al.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1023', name: 'Pedro Antônio Silva', role: 'Ciência da Computação' },
      { id: '854', name: 'Pedro Altobelli Teixeira Pinto', role: 'Engenharia de Computação' },
      { id: '1022', name: 'Matheus Aguiar de Jesus', role: 'Ciência da Computação' },
      { id: '1041', name: 'Eric Andrei Lima Possato', role: 'Engenharia de Computação' },
    ],
    advisor: 'Andrew Toshiaki Nakayama Kurauchi',
    longDescription: 'Desenvolvimento de um middleware de inteligência artificial integrado ao sistema Defense IA da Intelbras para detecção automatizada de armas de fogo em fluxos de vídeo RTSP, permitindo o monitoramento autônomo e o envio de alertas em tempo real.',
    tags: ['ArtificialIntelligence','ComputerVision','ObjectDetection','DeepLearning','SecuritySystems'],
    partner: 'Intelbras'
  },
  {
    id: '2024020018',
    title: 'Desempenho de carteira long-short de moedas estrangeiras com base em técnicas de machine learning',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.CIENCIA_DADOS,
    thumbnailUrl: 'https://www.infomoney.com.br/wp-content/uploads/2019/11/shutterstock_1190706364.jpg?fit=1280%2C853&quality=50&strip=all',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '848', name: 'Lucca Barufatti Velini Sanches', role: 'Engenharia de Computação' },
      { id: '1004', name: 'Alexandre Wever', role: 'Ciência da Computação' },
      { id: '1066', name: 'Gustavo Pacileo Borba', role: 'Engenharia Mecânica' },
      { id: '1029', name: 'André Barboza Braga de Melo', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabricio Jailson Barth',
    longDescription: 'Aprimoramento e implementação de uma plataforma de investimentos baseada em Machine Learning para o mercado cambial, utilizando engenharia de novos sinais financeiros e algoritmos de ranqueamento para otimizar o desempenho de uma carteira com estratégia Long-Short.',
    tags: ['DataScience','MachineLearning','PredictiveModeling','DataEngineering','QuantitativeFinance'],
    partner: 'Legacy Capital'
  },
  {
    id: '2024020019',
    title: 'Implementação de Inteligência Artificial para Identificação e Catalogação de Acervos do MASP',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://cdn.prod.website-files.com/67338a991d8aa120d15ef8c5/67d839c65463294e7ce7322a_Render.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '856', name: 'Pedro Osborn Mahfuz', role: 'Engenharia de Computação' },
      { id: '1016', name: 'Julia Karine Peres', role: 'Ciência da Computação' },
      { id: '1091', name: 'Julia Helen Toyama Cecon', role: 'Engenharia Mecatrônica' },
      { id: '1014', name: 'João Alfredo Cardoso Lamy', role: 'Ciência da Computação' },
    ],
    advisor: 'Marcelo Hashimoto',
    longDescription: 'Desenvolvimento de um sistema de Inteligência Artificial multimodal (Deep Learning, Visão Computacional e PLN) para automatizar a identificação, transcrição e catalogação do vasto acervo digitalizado do MASP, substituindo processos manuais por classificação inteligente de imagens, textos e áudios.',
    tags: ['ArtificialIntelligence','DeepLearning','ComputerVision','NLP','MuseumTech'],
    partner: 'MASP'
  },
  {
    id: '2024020020',
    title: 'Dynamic Adaptation of Graphical User Interfaces in Augmented Reality Based on Environmental Factors: Enhancing User Experience and Safety',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.SISTEMAS_INTERATIVOS,
    thumbnailUrl: 'https://portaldacomunicacao.com.br/wp-content/uploads/2023/10/NTT-Data.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1057', name: 'Pedro Bittar Barão', role: 'Engenharia de Computação' },
      { id: '1061', name: 'Rafael Melhado Araujo Lima', role: 'Engenharia de Computação' },
      { id: '1030', name: 'André Corrêa Santos', role: 'Engenharia de Computação' },
      { id: '829', name: 'Arthur Ferreira Carvalho', role: 'Engenharia de Computação' },
    ],
    advisor: 'Luciano Pereira Soares',
    longDescription: 'Desenvolvimento de uma solução de Realidade Aumentada com interfaces gráficas adaptativas que utilizam visão computacional e IA generativa para ajustar automaticamente posicionamento, cores e contraste com base em riscos de segurança, iluminação e oclusão de objetos no mundo real.',
    tags: ['AugmentedReality','UX','HumanComputerInteraction','ComputerVision','GenerativeAI'],
    partner: 'NTT Data Brasil'
  },
  {
    id: '2024020021',
    title: 'Identification of Flooding Incident Impacts Using Neural Networks',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://developer-blogs.nvidia.com/wp-content/uploads/2021/05/nvidia-eye-1000x600-1.png',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1015', name: 'João Lucas de Moraes Barros Cadorniga', role: 'Ciência da Computação' },
      { id: '1024', name: 'Pedro Vaz de Moraes Pertusi', role: 'Ciência da Computação' },
      { id: '1006', name: 'Eduardo Mendes Vaz', role: 'Ciência da Computação' },
      { id: '1003', name: 'Alexandre Magno Maciel dos Santos', role: 'Ciência da Computação' },
    ],
    advisor: 'Igor dos Santos Montagner',
    longDescription: 'Desenvolvimento de uma pipeline de código aberto que utiliza Redes Neurais Convolucionais (CNN) para processar imagens dos satélites Sentinel-1 e Sentinel-2, cruzando-as com dados populacionais para mapear e estimar o impacto de enchentes em tempo real para o planejamento urbano.',
    tags: ['ArtificialIntelligence','ConvolutionalNeuralNetworks','DeepLearning','SatelliteImagery','DataScience'],
    partner: 'Nvidia'
  },
  {
    id: '2024020022',
    title: 'Monitoramento e Análise de Recursos Multi-Cloud com Controles de Custo, KPIs e Segurança Cibernética',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: 'https://www.moneytimes.com.br/uploads/2020/01/pinpag.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1031', name: 'Antônio Amaral Egydio Martins', role: 'Engenharia de Computação' },
      { id: '1040', name: 'Enricco Gemha', role: 'Engenharia de Computação' },
      { id: '1002', name: 'Alan Matheus Alves Barbosa', role: 'Ciência da Computação' },
      { id: '1009', name: 'Esdras Gomes Carvalho', role: 'Ciência da Computação' },
    ],
    advisor: 'Rodolfo da Silva Avelino',
    longDescription: 'Otimização do ecossistema multi-cloud (AWS/Azure) da PinPag através da reestruturação de fluxos de observabilidade no Grafana, implementação de segurança preventiva (SemGrep e WAF) e consolidação de KPIs de custo e desempenho.',
    tags: ['InformationSystems','CloudInfrastructure','FinOps','Cybersecurity','Fintech'],
    partner: 'Pinpag'
  },
  {
    id: '2024020023',
    title: 'PROVA DE CONCEITO DE UM CHATBOT EM WHATSAPP PARA ATENDIMENTO AO CLIENTE',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.SOFTWARE,
    thumbnailUrl: 'https://www.syngenta.com.br/sites/g/files/kgtney466/files/media/image/2025/02/10/syngenta_show_rural_coopavel_2025.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1007', name: 'Enzo Quental Vieira de Campos', role: 'Ciência da Computação' },
      { id: '1059', name: 'Rafael Coca Leventhal', role: 'Engenharia de Computação' },
      { id: '1037', name: 'Caio Ribeiro de Paula', role: 'Engenharia de Computação' },
    ],
    advisor: 'Fabio Roberto de Miranda',
    longDescription: 'Desenvolvimento de uma Prova de Conceito (PoC) de um chatbot para WhatsApp integrado a um sistema de CRM para a Syngenta, utilizando LLMs para automação inteligente de dúvidas sobre programas de relacionamento.',
    tags: ['SoftwareDevelopment','Chatbot','LLM','GenerativeAI','AgileMethodology'],
    partner: 'Syngenta Seeds'
  },
  {
    id: '2024020024',
    title: 'Utilizando Inteligência Artificial para Potencializar Propostas Comerciais',
    description: '',
    semester: '2',
    year: 2024,
    category: ProjectCategory.AI,
    thumbnailUrl: 'https://dciber.org/wp-content/uploads/2022/12/maxresdefault.jpg',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.EXCELENCIA,
    students: [
      { id: '1019', name: 'Lucca Hiratsuca Costa', role: 'Ciência da Computação' },
      { id: '1018', name: 'Livia Tanaka', role: 'Ciência da Computação' },
      { id: '1054', name: 'Luiz Felipe Lazzaron', role: 'Engenharia de Computação' },
      { id: '1081', name: 'Enzo Francisco Klann Fonteyne', role: 'Engenharia Mecatrônica' },
    ],
    advisor: 'Andre Luiz Maciel Santana',
    longDescription: 'Desenvolvimento de uma ferramenta de IA generativa orquestrada com LangChain para equipes de vendas B2B, utilizando técnicas de RAG e o framework ReAct para automatizar, revisar e enriquecer propostas comerciais a partir de apresentações e dados internos.',
    tags: ['ArtificialIntelligence','GenerativeAI','LangChain','NLP','BusinessProductivity'],
    partner: 'Tivit'
  },
  {
    id: '2024010001',
    title: '',
    description: '',
    semester: '1',
    year: 2024,
    category: ProjectCategory.SISTEMAS_INFORMACAO,
    thumbnailUrl: '',
    galleryUrls: [
      '',
    ],
    awardType: AwardType.NENHUM,
    students: [
      { id: '0000', name: '', role: 'Engenharia Mecanica' },
      { id: '0000', name: '', role: 'Engenharia de Computação' },
      { id: '0000', name: '', role: 'Engenharia Mecatrônica' },
    ],
    advisor: '',
    longDescription: '',
    tags: ['','','','',''],
    partner: ''
  },
];
